## Web Scraping Forbes Global 500 (2016) Data

In [6]:
import awscli
import sys
import selenium
import unittest
import boto3
import pandas as pd
import tabulate
import time
import requests
import csv
import dataframe
from bs4 import BeautifulSoup
from tabulate import tabulate
from selenium import webdriver

In [14]:
browser = webdriver.Chrome(r"C:\Users\...\chromedriver.exe")
browser.get('https://fortune.com/global500/2016/search/')

In [17]:
#Find EIN filed
inputElement = browser.find_element_by_xpath("//*[@id='content']/div/div[2]/div/div[2]/div/div[2]/span[2]/select")
inputElement.send_keys('100 Rows')

In [18]:
#identify the table to scrape
table = browser.find_element_by_css_selector('div.rt-tbody')

In [19]:
datetime = time.strftime("%Y%m%d-%H%M%S")
filedirectory = 'C:/Users/Jeeho/Documents/Python Scripts/Capstone project/Web_Scrap/'
filename = 'fg500_2016_'
datetime = time.strftime("%Y%m%d%H%M%S")
file = "%s%s%s.csv"%(filedirectory,filename,datetime)

In [20]:
#create empty dataframe Test 2 : Included For Loop for next pages 
data =[]

#Use For Loop for Index

index = 1
while True:
    if index > 5:
        break
    try:
        print("Scraping Page number " + str(index))
        index = index + 1
        for row in table.find_elements_by_css_selector('div.rt-tr'):
            cols = data.append([cell.text for cell in row.find_elements_by_css_selector('div.rt-td.searchResults__cell--2Y7Ce')])

        time.sleep(4)
        next_button = browser.find_element_by_css_selector('div.-next')
        next_button.click()
    except Exception as e:
        print(e)
        break


data1 = pd.DataFrame(data, columns = ['rank','company','employees','revenue % change', 'profits($M)','profits % change','assets($M)'])

data1['year']=2016

print(data1)

browser.quit()

Scraping Page number 1
Scraping Page number 2
Scraping Page number 3
Scraping Page number 4
Scraping Page number 5
    rank                                company  employees revenue % change  \
0      1                                Walmart  2,300,000            -0.7%
1      2                             State Grid    927,839            -2.9%
2      3               China National Petroleum  1,589,508           -30.2%
3      4                          Sinopec Group    810,538           -34.1%
4      5                      Royal Dutch Shell     90,000           -36.9%
5      6                            Exxon Mobil     75,600           -35.6%
6      7                             Volkswagen    610,076           -11.9%
7      8                           Toyota Motor    348,877            -4.5%
8      9                                  Apple    110,000            27.9%
9     10                                     BP     79,800             -37%
10    11                     Berkshire Hathaway    331,000             8.3%
11    12                               McKesson     68,000             6.2%
12    13                    Samsung Electronics    319,000            -9.4%
13    14                               Glencore    102,388           -22.9%
14    15  Industrial & Commercial Bank of China    466,346             2.5%
15    16                                Daimler    284,015            -3.8%
16    17                     UnitedHealth Group    200,000            20.4%
17    18                             CVS Health    199,000              10%
18    19                             EXOR Group    303,247            -5.9%
19    20                         General Motors    215,000            -2.3%
20    21                             Ford Motor    199,000             3.8%
21    22                China Construction Bank    369,183             3.7%
22    23                                   AT&T    281,450            10.8%
23    24                                  Total     96,019           -32.4%
24    25             Hon Hai Precision Industry  1,060,000             1.6%
25    26                       General Electric    333,000            -5.3%
26    27   China State Construction Engineering    241,474             7.9%
27    28                      AmerisourceBergen     17,000            13.7%
28    29             Agricultural Bank of China    508,726             2.6%
29    30                                Verizon    177,700             3.6%
..   ...                                    ...        ...              ...
470  471                          National Grid     25,068              -7%
471  472                         Emirates Group     61,205            -3.7%
472  473                  CK Hutchison Holdings    270,000           567.6%
473  474                      Ultrapar Holdings     14,597           -21.1%
474  475               Community Health Systems    123,000             3.1%
475  476                                Arconic     60,000            -5.7%
476  477               Greenergy Fuels Holdings        594           -10.5%
477  478                               VTB Bank     92,882             -24%
478  479                    International Paper     56,000           -14.7%
479  480                       Emerson Electric    110,800            -9.1%
480  481                            Midea Group     93,299              -4%
481  482                                Telstra     36,165           -10.2%
482  483                                   Onex    144,000            -8.7%
483  484     China National Aviation Fuel Group     11,481           -38.9%
484  485                          Union Pacific     47,457            -9.1%
485  486                               Wolseley     38,464             0.8%
486  487                                  Amgen     17,900               8%
487  488                 H & M Hennes & Mauritz    104,634            -3.3%
488  489                         Shougang Group    114,807           -27.5%
489  490                           U.S. Bancorp     65,433             0.5%
490  491                           Unipol Group     13,242           -27.2%
491  492                       Alfresa Holdings     11,788            -2.5%
492  493                             Swiss Life      7,595            -4.5%
493  494                       Randstad Holding     29,750            -6.8%
494  495                               WH Group    105,000            -4.6%
495  496           Evergrande Real Estate Group     83,372            17.2%
496  497                                Staples     58,963            -6.4%
497  498                     Standard Chartered     84,076           -15.4%
498  499                   Rolls-Royce Holdings     50,500           -11.8%
499  500                             Old Mutual     64,043           -17.9%

    profits($M) profits % change  assets($M)  year
0       $14,694           -10.2%    $199,581  2016
1       $10,201             4.1%    $478,539  2016
2        $7,091           -56.7%    $621,242  2016
3        $3,595           -30.6%    $317,006  2016
4        $1,939             -87%    $340,157  2016
5       $16,150           -50.3%    $336,758  2016
6       $-1,520          -110.4%    $414,858  2016
7       $19,264            -2.5%    $422,029  2016
8       $53,394            35.1%    $290,479  2016
9       $-6,482          -271.5%    $261,832  2016
10      $24,083            21.2%    $552,257  2016
11       $2,258              53%     $56,563  2016
12      $16,532           -24.6%    $206,585  2016
13      $-4,964          -315.1%    $128,485  2016
14      $44,098            -1.5%  $3,420,257  2016
15       $9,345             1.2%    $235,886  2016
16       $5,813             3.5%    $111,383  2016
17       $5,237            12.8%     $93,657  2016
18         $825            92.6%    $170,419  2016
19       $9,687           145.3%    $194,520  2016
20       $7,373           131.3%    $224,925  2016
21      $36,303            -1.8%  $2,825,781  2016
22      $13,345           114.4%    $402,672  2016
23       $5,087            19.9%    $224,484  2016
24       $4,627             7.4%     $70,287  2016
25      $-6,126          -140.2%    $492,692  2016
26       $2,251             8.3%    $166,279  2016
27        $-135          -148.8%     $27,736  2016
28      $28,735            -1.3%  $2,739,835  2016
29      $17,879            85.8%    $244,640  2016
..          ...              ...         ...   ...
470      $3,901            20.1%     $84,694  2016
471      $1,940            56.5%     $32,448  2016
472     $15,295           120.2%    $133,285  2016
473        $451           -14.5%      $5,301  2016
474        $158            71.7%     $26,861  2016
475       $-322          -220.1%     $36,528  2016
476          $4           -69.6%      $2,604  2016
477        $175            64.7%    $187,170  2016
478        $938              69%     $30,587  2016
479      $2,710            26.2%     $22,088  2016
480      $2,022            24.5%     $19,841  2016
481      $3,519           -10.3%     $31,078  2016
482       $-573                -     $35,810  2016
483        $334             255%      $4,875  2016
484      $4,772            -7.9%     $54,600  2016
485        $332           -59.8%     $11,674  2016
486      $6,939            34.5%     $71,576  2016
487      $2,499           -15.3%      $9,843  2016
488       $-320         -9910.5%     $67,291  2016
489      $5,879             0.5%    $421,853  2016
490        $302            18.2%     $97,512  2016
491        $291            39.7%     $11,154  2016
492        $906             1.9%    $189,120  2016
493        $576            27.6%      $7,939  2016
494        $786             2.6%     $14,301  2016
495      $2,474             -10%    $116,582  2016
496        $379           181.9%     $10,172  2016
497     $-2,194            -184%    $640,483  2016
498        $127            11.6%     $32,899  2016
499        $938            -2.1%    $196,810  2016

[500 rows x 8 columns]

In [21]:
data1.to_csv(file, header=True, line_terminator='\n')