In [1]:
import re
import pandas as pd
import numpy as np
import dataframe
from bs4 import BeautifulSoup
import socket 
import time
import requests
from selenium import webdriver
from urllib.parse import quote_plus
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException

import urllib.request
import urllib.parse

In [2]:
ceo_df = pd.read_csv(r'C:\Users\Jeeho\Documents\Python Scripts\Capstone project\Web_Scrap\fg500_CEOs_v4_all(Apr_10_2020).csv')

In [3]:
c_sample = ceo_df['CEO']

In [4]:
browser = webdriver.Chrome(r"C:\Users\Jeeho\AppData\Local\Programs\Python\Python36\chromedriver.exe")


ceo_list = c_sample
values =[]
df = pd.DataFrame(columns = ['ceo'])

for ceo in ceo_list:
    baseUrl = 'https://www.google.com/search?q='
    browser.get(baseUrl + ceo)
    table = browser.find_elements_by_css_selector('div.ifM9O') 

    for row in table:
        ceo = str(([c.text for c in row.find_elements_by_css_selector('div.kno-ecr-pt.PZPZlf.gsmt.i8lZMc')])).strip('[]').strip("''")
    for row in table:
        value = str(([c.text for c in row.find_elements_by_css_selector('div.Z1hOCe')])).strip('[]').strip("''")
    if not table:
        value = 'Null'
    
    values.append(value)
    
    s = pd.Series(ceo,index=df.columns)
    vs = pd.Series(values) 

    df = df.append(s,ignore_index=True)

    time.sleep(2) # To make the scraping slower
    
    
df['value'] = vs  
print(df)

browser.close()

                                  ceo  \
0                       Doug McMillon
1                        Dai Houliang
2                     Ben van Beurden
3
4
5                      Amin H. Nasser
6                          Bob Dudley
7                        Darren Woods
8                       Herbert Diess
9                         Akio Toyoda
10                           Tim Cook
11                     Warren Buffett
12                         Jeff Bezos
13
14
15                    Ivan Glasenberg
16                     Brian S. Tyler
17                      Ola Källenius
18                     Larry J. Merlo
19                   Patrick Pouyanné
20
21                        Jeremy Weir
22                          Terry Gou
23                        John Elkann
24              Randall L. Stephenson
25
26                   Steven H. Collis
27                         Mike Wirth
28                         Ma Mingzhe
29                        Jim Hackett
..                                ...
469                   Richard M. Tsai
470                   Miguel Patricio
471
472                  Revathi Advaithi
473                       Zhang Yalin
474
475                    Jörn H. Werner
476                  Florent Menrgaux
477               Philip W. Chronican
478                   Dirk Van de Put
479                    Kasper Rørsted
480                     Li Hongshuang
481                     Wiebe Draijer
482
483                       Xu Xianping
484                  Andrew J. Cecere
485                  Jeffrey Gennette
486      Miguel Eduardo Padilla Silva
487                     Todd J. Vasos
488                         H.C. Shin
489                Gerald W. Schwartz
490                     Bao Lang Chen
491               Philippe Petitcolin
492              Willem A.J. van Duin
493                   Rajesh J. Mehta
494                  Leon J. Topalian
495                      Darryl White
496
497  Frederico Pinheiro Fleury Curado
498                     Benoît Potier

                                                 value
0    Born: October 17, 1966 (age 53 years), Memphis...
1                                                 Null
2    Born: April 23, 1958 (age 61 years), Netherlan...
3
4
5    Born: 1960 (age 60 years)', 'Nationality: Saud...
6    Born: September 14, 1955 (age 64 years), Queen...
7    Born: Wichita, KS', 'Nationality: American', '...
8    Born: October 24, 1958 (age 61 years), Munich,...
9    Born: May 3, 1956 (age 63 years), Nagoya, Aich...
10   Born: November 1, 1960 (age 59 years), Mobile,...
11   Born: August 30, 1930 (age 89 years), Omaha, N...
12   Born: January 12, 1964 (age 56 years), Albuque...
13
14
15   Born: January 1957 (age 63 years), Johannesbur...
16                                                Null
17   Born: June 11, 1969 (age 50 years), Västervik,...
18   Born: 1956 (age 64 years), Pittsburgh, PA', 'N...
19   Born: June 24, 1963 (age 56 years), Le Petit-Q...
20
21   Born: 1964 (age 56 years), Melbourne, Australi...
22   Born: October 18, 1950 (age 69 years), Banqiao...
23   Born: April 1, 1976 (age 44 years), New York, ...
24   Born: April 22, 1960 (age 59 years), Oklahoma ...
25
26   Born: 1961 (age 59 years), South Africa', 'Edu...
27   Born: 1960 (age 60 years)', 'Education: Univer...
28   Born: December 1955 (age 64 years), China', 'E...
29   Born: April 22, 1955 (age 64 years), Columbus,...
..                                                 ...
469                                               Null
470  Nationality: Portuguese', 'Predecessor: Bernar...
471
472                                               Null
473  Born: April 19, 1981, Dalian, China', 'Died: F...
474
475                                               Null
476                                               Null
477                                               Null
478  Born: 1959 (age 61 years), Mechelen, Belgium',...
479  Born: February 24, 1962 (age 58 years), Aarhus...
480                                               Null
481  Born: August 27, 1965 (age 54 years), Enschede...
482
483  Born: October 1954 (age 65 years), Longhui Cou...
484                                               Null
485  "Movies: The 92nd Annual Macy's Thanksgiving D...
486                                               Null
487                                               Null
488                                               Null
489  Born: November 24, 1941 (age 78 years), Winnip...
490                                               Null
491  Born: September 28, 1952 (age 67 years), Banno...
492                                               Null
493                                               Null
494                                               Null
495                    Education: Ivey Business School
496
497                                               Null
498  Born: 1957 (age 63 years), Mulhouse, France', ...

[499 rows x 2 columns]

In [17]:
#reindex the data
re_index = pd.Series(range(1,500))  
df = df.set_index([re_index])

In [18]:
display(df)

,ceo,value
1,Doug McMillon,"Born: October 17, 1966 (age 53 years), Memphis, TN', 'Nationality: American', 'Spouse: Shelley McMillon', 'Education: Bentonville High School, Sam M. Walton College of Business, The University of Tulsa, University of Arkansas', 'Children: Blake McMillon, Spencer McMillon', 'Parents: Morris McMillon, Laura McMillon"
2,Dai Houliang,Null
3,Ben van Beurden,"Born: April 23, 1958 (age 61 years), Netherlands', 'Full name: Bernardus Cornelis Adriana Margriet van Beurden', 'Spouse: Stacey van Beurden', 'Children: 4', 'Term: January 2014–present', 'Education: Delft University of Technology (TU Delft)"
4,,
5,,
6,Amin H. Nasser,"Born: 1960 (age 60 years)', 'Nationality: Saudi', 'Education: جامعة الملك فهد للبترول والمعادن"
7,Bob Dudley,"Born: September 14, 1955 (age 64 years), Queens, New York, NY', 'Nationality: American', 'Spouse: Mary Dudley', 'Citizenship: United Kingdom; United States', 'Title: Former Group Chief Executive of BP', 'Education: University of Illinois at Urbana-Champaign, MORE"
8,Darren Woods,"Born: Wichita, KS', 'Nationality: American', 'Spouse: Kathryn Woods', 'Predecessor: Rex W. Tillerson', 'Education: Kellogg School of Management, Texas A&M University"
9,Herbert Diess,"Born: October 24, 1958 (age 61 years), Munich, Germany', 'Education: Technische Universität München (1987), MORE', 'Board member of: Audi, Volkswagen Group, SEAT, Škoda Auto, Porsche Holding"
10,Akio Toyoda,"Born: May 3, 1956 (age 63 years), Nagoya, Aichi, Japan', 'Nationality: Japanese', 'Children: 2', 'Education: Babson College, Keio University', 'Parents: Shoichiro Toyoda, Hiroko Mitsui', 'Grandparents: Kiichiro Toyoda, Hatako Toyoda"
11,Tim Cook,"Born: November 1, 1960 (age 59 years), Mobile, AL', 'Height: 6′ 0″', 'Net worth: US$ 1.3 billion (2015)', 'Education: The Fuqua School of Business (1988), MORE', 'Parents: Geraldine Cook, Donald Cook', 'Siblings: Gerald Cook, Michael Cook"
12,Warren Buffett,"Born: August 30, 1930 (age 89 years), Omaha, NE', 'Net worth: 74.3 billion USD (2020)', 'Education: Columbia Business School (1950–1951), MORE', 'Spouse: Astrid Menks (m. 2006), Susan Buffett (m. 1952–2004)"
13,Jeff Bezos,"Born: January 12, 1964 (age 56 years), Albuquerque, NM', 'Height: 5′ 7″', 'Nationality: American', 'Net worth: 124 billion USD (2020)', 'Education: Princeton University (1986), River Oaks Elementary School, Miami Palmetto Senior High School', 'Parents: Ted Jorgensen, Miguel Bezos, Jacklyn Bezos"
14,,
15,,
16,Ivan Glasenberg,"Born: January 1957 (age 63 years), Johannesburg, South Africa', 'Net worth: 2.8 billion USD (2020)', 'Spouse: Elana Glasenberg', 'Children: 2', 'Education: Marshall Business School, USC, University of the Witwatersrand, Johannesburg, University of Southern California', 'Nationality: Swiss, Israeli, South African, Australian"
17,Brian S. Tyler,Null
18,Ola Källenius,"Born: June 11, 1969 (age 50 years), Västervik, Sweden', 'Nationality: Swedish', 'Employer: Daimler AG', 'Education: University of St. Gallen, Stockholm School of Economics, Danderyds gymnasium"
19,Larry J. Merlo,"Born: 1956 (age 64 years), Pittsburgh, PA', 'Nationality: American', 'Spouse: Lee Ann Merlo', 'Education: University of Pittsburgh School of Pharmacy (1978)', 'Residence: Rhode Island"
20,Patrick Pouyanné,"Born: June 24, 1963 (age 56 years), Le Petit-Quevilly, France', 'Education: École Polytechnique"
21,,
22,Jeremy Weir,"Born: 1964 (age 56 years), Melbourne, Australia', 'Education: University of Melbourne', 'Predecessor: Claude Dauphin"
23,Terry Gou,"Born: October 18, 1950 (age 69 years), Banqiao District, Taipei, Taiwan', 'Net worth: 5.8 billion USD (2020)', 'Spouse: Delia Tseng (m. 2008), Serena Lin (m. 1974–2005)', 'Education: Taipei College of Maritime Technology (1966–1971), New Taipei Municipal Panchiao Senior High School', 'Children: Gou Shou-zheng, Gou Xiao-ling, Gou Shou-shan, Gou Xiao-ru', 'Organizations founded: Hon Hai Precision Industry Co., Ltd., Hon Hai Precision, Yonglin Foundation, FIH Mobile Limited"
24,John Elkann,"Born: April 1, 1976 (age 44 years), New York, NY', 'Spouse: Lavinia Borromeo (m. 2004)', 'Education: Polytechnic University of Turin', 'Siblings: Lapo Elkann, Ginevra Elkann, Anna de Pahlen, Maria de Pahlen, Pietro de Pahlen, Tatiana de Pahlen, Sofia de Pahlen', 'Children: Oceano Noah Elkann, Vita Talita Elkann, Leone Mosé Elkann', 'Parents: Alain Elkann, Margherita Agnelli"
25,Randall L. Stephenson,"Born: April 22, 1960 (age 59 years), Oklahoma City, OK', 'Nationality: American', 'Spouse: Lenise Stephenson', 'Children: 2', 'Residence: Dallas, TX', 'Education: The University of Oklahoma, University of Central Oklahoma"
26,,
27,Steven H. Collis,"Born: 1961 (age 59 years), South Africa', 'Education: University of the Witwatersrand, Johannesburg', 'Predecessor: R. David Yost"
28,Mike Wirth,"Born: 1960 (age 60 years)', 'Education: University of Colorado Boulder"
29,Ma Mingzhe,"Born: December 1955 (age 64 years), China', 'Education: Zhongnan University of Economics and Law', 'Organization founded: Ping An Insurance"
30,Jim Hackett,"Born: April 22, 1955 (age 64 years), Columbus, OH', 'Nationality: American', 'Education: University of Michigan (1977)', 'Spouse: Kathy Hackett', 'Residence: Grand Rapids, Michigan, U.S', 'Children: 2"
31,Tian Guoli,Null
32,Mary T. Barra,"Born: December 24, 1961 (age 58 years), Waterford, MI', 'Nationality: American', 'Spouse: Anthony E. Barra', 'Education: Stanford Graduate School of Business (1988–1990), Kettering University, Mott High School', 'Children: Nicholas Barra, Rachel Barra', 'Parents: Ray Makela, Eva Makela"
33,Takehiko Kakiuchi,"Born: July 31, 1955 (age 64 years), Hyogo, Japan', 'Education: Hyogo Prefectural Nagata High School"
34,Takahiro Hachigo,"Born: May 19, 1959 (age 60 years), Japan', 'Alma mater: Tokyo City University', 'Board member of: Honda Motor Company"
35,W. Craig Jelinek,"Born: August 8, 1952 (age 67 years), California', 'Nationality: American', 'Education: San Diego State University (1975)', 'Predecessor: James Sinegal"
36,Zhou Mubing,Null
37,Sundar Pichai,"Born: June 10, 1972 (age 47 years), Madurai, India', 'Spouse: Anjali Pichai', 'Education: Wharton School of the University of Pennsylvania, MORE', 'Children: Kavya Pichai, Kiran Pichai', 'Nationality: American, Indian', 'Parents: Regunatha Pichai, Lakshmi Pichai"
38,Michael C. Kaufmann,Null
39,,
40,Stefano Pessina,"Born: June 4, 1941 (age 78 years), Pescara, Italy', 'Net worth: 8.8 billion USD (2020)', 'Children: 2', 'Partner: Ornella Barra (1985–)', 'Board member of: Walgreens Boots Alliance', 'Education: University of Milan, Politecnico di Milano"
41,Jamie Dimon,"Born: March 13, 1956 (age 64 years), New York, NY', 'Nationality: American', 'Net worth: 1.2 billion USD (2020)', 'Spouse: Judith Kent (m. 1983)', 'Children: Laura Dimon, Julia Dimon, Kara Leigh Dimon', 'Education: Harvard Business School (1982), Tufts University, Browning School"
42,,
43,,
44,Liu Liange,Null
45,Oliver Bäte,"Born: March 1, 1965 (age 55 years), Bergisch Gladbach, Germany', 'Education: University of Cologne (1988–1993), NYU Stern School of Business (1988–1993)"
46,Thomas Buberl,"Born: March 24, 1973 (age 47 years), Cologne, Germany', 'Education: WHU - Otto Beisheim School of Management, Lancaster University, University of St. Gallen"
47,Rodney McMullen,"Born: July 25, 1960 (age 59 years), Pineville, KY', 'Education: University of Kentucky', 'Predecessor: David Dillon', 'Board member of: Cincinnati Financial, Kroger"
48,H. Lawrence Culp Jr.,"Born: 1964 (age 56 years), Washington, D.C.', 'Nationality: American', 'Children: 3', 'Title: Chairman and CEO, General Electric', 'Predecessor: John L. Flannery', 'Education: Washington College, Harvard Business School"
49,Hugh R. Frater,Null
50,,
51,,
52,Masatsugu Nagato,"Born: November 18, 1948 (age 71 years), Otaru, Hokkaido, Japan', 'Education: Hitotsubashi University', 'Predecessor: Taizo Nishimuro"
53,Harald Krüger,"Born: October 13, 1965 (age 54 years), Freiburg im Breisgau, Germany', 'Education: RWTH Aachen University (1991), MORE"
54,Greg Garland,"Spouse(s): married', 'Education: Texas A&M University', 'Children: 4"
55,Zhang Zongyan,Null
56,Li Yue,"Born: 1959 (age 61 years), China', 'Education: Beijing University of Posts and Telecommunications"
57,Joseph W. Gorder,"Born: May 1957 (age 62 years)', 'Education: University of Missouri-St. Louis, Our Lady of the Lake School of Business"
58,Brian Moynihan,"Born: October 9, 1959 (age 60 years), Marietta, OH', 'Nationality: American', 'Spouse: Susan Berry', 'Children: 3', 'Education: Notre Dame Law School (1984), Brown University (1981), University of Notre Dame', 'Siblings: Patrick Moynihan, Kathryn Moynihan"
59,Chen Fenjian,Null
60,Satya Nadella,"Born: August 19, 1967 (age 52 years), Hyderabad, India', 'Title: CEO of Microsoft', 'Spouse: Anupama Nadella (m. 1992)', 'Education: University of Wisconsin-Milwaukee (1990), MORE', ""Books: Hit Refresh: The Quest to Rediscover Microsoft's Soul and Imagine a Better Future for Everyone"", 'Children: Tara Nadella, Zain Nadella, Divya Nadella"
61,Ren Zhengfei,"Born: October 25, 1944 (age 75 years), Zhenning Buyei and Miao Autonomous County, Anshun, China', 'Height: 5′ 8″', 'Spouse: Yao Ling', 'Net worth: 1.1 billion USD (2020)', 'Education: Chongqing University', 'Children: Meng Wanzhou, Annabel Yao, Ren Ping"
62,Craig Menear,"Born: 1958 (age 62 years), Flint, MI', 'Nationality: American', 'Education: Eli Broad College of Business, Central High School, Michigan State University"
63,,
64,Jun Sawada,"Born: July 30, 1955 (age 64 years)', 'Predecessor: Hiroo Unoura"
65,Masahiro Okafuji,"Born: December 12, 1949 (age 70 years), Osaka, Osaka, Japan"
66,Hiroto Saikawa,"Born: November 14, 1953 (age 66 years), Japan"
67,Zheng Zhijie,"Born: May 1958 (age 61 years)', 'Education: Dongbei University of Finance and Economics', 'Party: Communist Party of China"
68,Dave Calhoun,"Born: April 18, 1957 (age 62 years), Philadelphia, PA', 'Nationality: American', ""Books: How Companies Win: Profiting from Demand-Driven Business Models No Matter What Business You're In"", 'Education: Orefield Middle School, Pamplin College of Business, Virginia Polytechnic Institute and State University', ""Albums: Momentary Mutiny, Day Drinkin', Salmon Chanted Harbor"", 'Children: Corey Calhoun, Amy Calhoun, Devon Calhoun, Jessica Calhoun"
69,Charles W. Scharf,"Born: 1965 (age 55 years)', 'Nationality: American', 'Organization: Visa U.S.A', 'Education: New York University, Johns Hopkins University"
70,Joe Kaeser,"Born: June 23, 1957 (age 62 years), Arnbruck, Germany', 'Spouse: Rosemarie Kaeser', 'Education: Ostbayerische Technische Hochschule (OTH) Regensburg"
71,Michael Corbat,"Born: May 2, 1960 (age 59 years), Bristol, CT', 'Nationality: American', 'Spouse: Donna Corbat', 'Education: Harvard University (1983)"
72,Gary R. Heminger,"Born: Tiffin, OH', 'Education: University of Dayton (1982), Tiffin University (1976)"
73,Tae-Won Chey/Dong-Hyun Jang,Null
74,Roberto da Cunha Castello Branco,Null
75,Brian L. Roberts,"Born: June 28, 1959 (age 60 years), Philadelphia, PA', 'Nationality: American', 'Net worth: 1.7 billion USD (2020)', 'Spouse: Aileen Roberts', 'Education: Wharton School of the University of Pennsylvania, University of Pennsylvania, Germantown Academy', 'Children: Tucker Roberts, Sarah Roberts"
76,Ulf Mark Schneider,"Born: September 9, 1965 (age 54 years), Neuwied, Germany', 'Nationality: German', 'Predecessor: Paul Bulcke', 'Citizenship: German and American', 'Education: Harvard Business School, University of St. Gallen"
77,Volkmar Denner,"Born: November 30, 1956 (age 63 years), Uhingen, Germany', 'Education: University of Stuttgart (1985), University of Stuttgart (1981)', 'Appointed by: Angela Merkel"
78,Andreas Schierenbeck,Null
79,Gail Koziara Boudreaux,"Born: 1960 (age 60 years)', 'Spouse: Terry Boudreaux (m. 1989)', 'Children: 2 sons', 'Education: Chicopee Comprehensv High Sch, Columbia University, Columbia Business School, Dartmouth College"
80,Wang Xiangming,Null
81,Alexandre Bompard,"Born: October 4, 1972 (age 47 years), Saint-Étienne, France', 'Spouse: Charlotte Bompard', 'Predecessor: Georges Plassat', 'Board member of: Fnac', ""Education: École Nationale d'Administration (1997–1999), Sciences Po"""
82,Li Shaozhu,Null
83,Claudio Descalzi,"Born: 1955 (age 65 years), Milan, Italy', 'Education: University of Milan"
84,Michael S. Dell,"Born: February 23, 1965 (age 55 years), Houston, TX', 'Spouse: Susan Dell (m. 1989)', 'Education: Memorial Senior High School, The University of Texas at Austin, Herod Elementary School', 'Children: Alexa Dell, Zachary Dell, Kira Dell, Juliette Dell', 'Parents: Alexander Dell, Lorraine Charlotte Dell"
85,José Antonio Alvarez (José Antonio Álvarez Álvarez),"Born: January 6, 1960 (age 60 years), León, Spain', 'Predecessor: Javier Marín"
86,Igor Sechin,"Born: September 7, 1960 (age 59 years), Russian Soviet Federative Socialist Republic', 'Height: 5′ 9″', 'Spouse: Olga Rozhkova (m. 2011–2017)', 'Education: Saint Petersburg State University', 'Children: Inga Sechina, Ivan Sechin', 'Nationality: Russian, Soviet"
87,Xu Liuping,Null
88,Ning Gaoning,"Born: November 9, 1958 (age 61 years), Binzhou, China', 'Education: Joseph M. Katz Graduate School of Business, Shandong University, University of Pittsburgh"
89,Francesco Starace,"Born: 1955 (age 65 years), Rome, Italy', 'Education: Politecnico di Milano"
90,Timotheus Höttges,"Born: September 18, 1962 (age 57 years), Solingen, Germany', 'Education: University of Cologne"
91,Philippe Brassac,"Born: August 31, 1959 (age 60 years), Nîmes, France', 'Education: ENSAE Paris', 'Predecessor: Jean-Paul Chifflet"
92,Philippe Donnet,"Born: July 26, 1960 (age 59 years), Suresnes, France', 'Education: École Polytechnique"
93,Liu Qitao,Null
94,,
95,Octavio Romero Oropeza,"Born: January 20, 1959 (age 61 years), Jalapa"
96,Carlos Tavares,"Born: August 14, 1958 (age 61 years), Lisbon, Portugal', 'Nationality: Portuguese', 'Education: École Centrale Paris (1981)"
97,Yan Hao,Null
98,Masayoshi Son,"Born: August 11, 1957 (age 62 years), Tosu, Saga, Japan', 'Nationality: Japanese', 'Net worth: 20.3 billion USD (2020)', 'Children: 2', 'Spouse: Masami Ohno (m. 1979)', 'Education: University of California, Berkeley (1980), MORE"
99,John Flint,"Born: June 1968 (age 51 years), Yorkshire, United Kingdom', 'Successor: Noel Quinn', 'Predecessor: Stuart Gulliver', 'Children: 2', 'Title: CEO, HSBC', 'Education: University of Portsmouth, Giggleswick School"
100,C. Marc Doyle,Null
101,Liu Aili,Null
102,Toshiaki Higashihara,Null
103,,
104,Jean-Laurent Bonnafé,"Born: July 14, 1961 (age 58 years), Clichy, France', 'Education: École Polytechnique, Lycée Louis-le-Grand"
105,Tsutomu Sugimori,Null
106,,
107,Wang Xiangxi,Null
108,Michael L. Tipsord,"Born: June 20, 1959 (age 60 years), Illinois', 'Education: Illinois Wesleyan University (1981), University of Illinois at Urbana-Champaign"
109,Alex Gorsky,"Born: May 24, 1960 (age 59 years), Kansas City, KS', 'Nationality: American', 'Salary: US$ 20.1 million (2018); US$ 29.8 million (2017)', 'Education: Wharton School of the University of Pennsylvania, United States Military Academy', 'Children: Nicholas Gorsky', 'Parents: Albert Gorsky, Loretta Gorsky"
110,Jean-Bernard Lévy,"Born: March 18, 1955 (age 65 years), Suresnes, France', 'Education: École Polytechnique, Télécom Paris', 'Parents: Monique Herzog, Claude Lévy"
111,Meng Zhenping,Null
112,Tang Fuping,Null
113,Eldar Sætre,"Born: February 8, 1956 (age 64 years), Vartdal, Norway', 'Education: NHH Norwegian School of Economics', 'Siblings: Oddrun Godø"
114,Ginni Rometty,"Born: July 29, 1957 (age 62 years), Chicago, IL', 'Full name: Virginia Marie Rometty', 'Nationality: American', 'Spouse: Mark Anthony Rometty', 'Education: Robert R. McCormick School of Engineering and Applied Science at Northwestern', 'Siblings: Joe Nicosia"
115,Martin Brudermüller,"Born: May 5, 1961 (age 58 years), Stuttgart, Germany', 'Education: Karlsruhe Institute of Technology', 'Predecessor: Kurt Bock', 'Term: 2018"
116,,
117,Sanjiv Singh,Null
118,Motoya Okada,"Born: June 17, 1951 (age 68 years), Yokkaichi, Mie, Japan', 'Education: Babson College', 'Parents: Takuya Okada', 'Siblings: Katsuya Okada"
119,Wang Wenyin,"Born: 1968 (age 52 years), Anhui, China', 'Net worth: 8.1 billion USD (2020)', 'Education: Anhui Qianshan Yezhai Middle School, Nanjing University', 'Organization founded: Amer International Group"
120,Lakshmi Mittal,"Born: June 15, 1950 (age 69 years), Sadulpur, India', 'Nationality: Indian', 'Net worth: 8.9 billion USD (2020)', 'Spouse: Usha Mittal', ""Education: St. Xavier's College, Kolkata"", 'Children: Vanisha Mittal, Aditya Mittal"
121,,
122,Brian Cornell,"Born: 1958 (age 62 years), Queens, New York, NY', 'Spouse: Martha Cornell', 'Predecessor: Gregg W. Steinhafel', 'Known for: Chairman & CEO of Target', 'Education: UCLA Anderson School of Management, University of California, Los Angeles', 'Children: Megan Cornell, Jonathan Cornell"
123,Guillaume Faury,"Born: February 22, 1968 (age 52 years), Cherbourg-Octeville, Cherbourg-en-Cotentin, France', ""Education: Institut supérieur de l'aéronautique et de l'espace, École nationale supérieure de l'aéronautique et de l'espace"""
124,Frank Appel,"Born: July 29, 1961 (age 58 years), Hamburg, Germany', 'Predecessor: Klaus Zumwinkel', 'Education: ETH Zürich (2001), Ludwig Maximilian University of Munich"
125,Hiroshi Shimizu,"Born: March 28, 1903', 'Died: June 23, 1966, Ukyo Ward, Kyoto, Japan', 'Education: Hokkaido University', 'Other name: Takahiko Minamoto, Umihiko Yuhara', 'Books: Japan and Singapore in the world economy"
126,Isabelle Kocher,"Born: December 9, 1966 (age 53 years), Neuilly-sur-Seine, France', 'Children: 5', 'Spouse: Laurent Kocher (m. 1989)', 'Education: École Normale Supérieure (1987), Mines ParisTech"
127,Frans Muller,"Education: Erasmus University Rotterdam', 'Predecessor: Dick Boer"
128,Brickman David M CPA,"Address: 270 Madison Ave # 1500, New York, NY 10016', 'Phone: (212) 687-7215"
129,Xu Heyi,Null
130,Chansin Treenuchagron,Null
131,Kazuhiro Tsuga,"Born: November 14, 1956 (age 63 years), Osaka, Osaka, Japan', 'Predecessor: Fumio Ōtsubo', 'Employer: Panasonic', 'Title: President', 'Education: University of California, Santa Barbara (1986), Osaka University (1979)"
132,David P. Abney,"Born: 1956 (age 64 years), Greenwood, MS', 'Spouse: Sherry Abney', 'Education: Delta State University, Pillow Academy"
133,Marvin Ellison,"Born: 1966 (age 54 years)', 'Nationality: American', 'Spouse: Sharyn Ellison', 'Profession: Musician', ""Education: Haywood High School, Emory University, Emory University's Goizueta Business School, University of Memphis"", 'Children: Donavan Ellison"
134,Yu Xubo,Null
135,Bob Swan,"Born: May 9, 1960 (age 59 years), Syracuse, NY', 'Spouse(s): married', 'Children: 2', 'Employer: Intel', 'Board member of: Intel Corporation, eBay', 'Education: Corcoran High School, Binghamton University, University at Buffalo School of Management"
136,Megan Brennan,"Born: 1961 (age 59 years), Pottsville, PA', 'Office: United States Postmaster General since 2015', 'Party: Democratic Party', 'Education: MIT Sloan School of Management, Immaculata University"
137,Chang Zhenming,"Born: October 1956 (age 63 years), China', 'Parents: Chang Dong', 'Education: Tsinghua University High School, Beijing International Studies University', 'People also search for: Larry Yung, Chang Dong, Qingping Li, Qian Zhang, Deshun Sun, Guoqiang Cao, Guoxin Su"
138,Xu Jiayin,"Born: October 9, 1958 (age 61 years), Taikang County, Zhoukou, China', 'Nationality: Chinese', 'Net worth: 23.3 billion USD (2020)', 'Spouse: Ding Yumei (m. 1983)', 'Education: Wuhan University of Science and Technology', 'Children: Xu Xihao, Xu Zhijian"

Rename the unnamed column as index

In [48]:
#ceo list from 1-266
df_1 = df.iloc[0:266]

#ceo list from 267 to 500
df_2 = df.iloc[266:499]

#reindex the df_2
re_index2 = pd.Series(range(268,501))  
df_2 = df_2.set_index([re_index2])

#Merge the reindexed lists
df=df_1.append(df_2, ignore_index=False)

                                                               ceo  \
1    Doug McMillon
2    Dai Houliang
3    Ben van Beurden
4
5
6    Amin H. Nasser
7    Bob Dudley
8    Darren Woods
9    Herbert Diess
10   Akio Toyoda
11   Tim Cook
12   Warren Buffett
13   Jeff Bezos
14
15
16   Ivan Glasenberg
17   Brian S. Tyler
18   Ola Källenius
19   Larry J. Merlo
20   Patrick Pouyanné
21
22   Jeremy Weir
23   Terry Gou
24   John Elkann
25   Randall L. Stephenson
26
27   Steven H. Collis
28   Mike Wirth
29   Ma Mingzhe
30   Jim Hackett
31   Tian Guoli
32   Mary T. Barra
33   Takehiko Kakiuchi
34   Takahiro Hachigo
35   W. Craig Jelinek
36   Zhou Mubing
37   Sundar Pichai
38   Michael C. Kaufmann
39
40   Stefano Pessina
41   Jamie Dimon
42
43
44   Liu Liange
45   Oliver Bäte
46   Thomas Buberl
47   Rodney McMullen
48   H. Lawrence Culp Jr.
49   Hugh R. Frater
50
51
52   Masatsugu Nagato
53   Harald Krüger
54   Greg Garland
55   Zhang Zongyan
56   Li Yue
57   Joseph W. Gorder
58   Brian Moynihan
59   Chen Fenjian
60   Satya Nadella
61   Ren Zhengfei
62   Craig Menear
63
64   Jun Sawada
65   Masahiro Okafuji
66   Hiroto Saikawa
67   Zheng Zhijie
68   Dave Calhoun
69   Charles W. Scharf
70   Joe Kaeser
71   Michael Corbat
72   Gary R. Heminger
73   Tae-Won Chey/Dong-Hyun Jang
74   Roberto da Cunha Castello Branco
75   Brian L. Roberts
76   Ulf Mark Schneider
77   Volkmar Denner
78   Andreas Schierenbeck
79   Gail Koziara Boudreaux
80   Wang Xiangming
81   Alexandre Bompard
82   Li Shaozhu
83   Claudio Descalzi
84   Michael S. Dell
85   José Antonio Alvarez (José Antonio Álvarez Álvarez)
86   Igor Sechin
87   Xu Liuping
88   Ning Gaoning
89   Francesco Starace
90   Timotheus Höttges
91   Philippe Brassac
92   Philippe Donnet
93   Liu Qitao
94
95   Octavio Romero Oropeza
96   Carlos Tavares
97   Yan Hao
98   Masayoshi Son
99   John Flint
100  C. Marc Doyle
101  Liu Aili
102  Toshiaki Higashihara
103
104  Jean-Laurent Bonnafé
105  Tsutomu Sugimori
106
107  Wang Xiangxi
108  Michael L. Tipsord
109  Alex Gorsky
110  Jean-Bernard Lévy
111  Meng Zhenping
112  Tang Fuping
113  Eldar Sætre
114  Ginni Rometty
115  Martin Brudermüller
116
117  Sanjiv Singh
118  Motoya Okada
119  Wang Wenyin
120  Lakshmi Mittal
121
122  Brian Cornell
123  Guillaume Faury
124  Frank Appel
125  Hiroshi Shimizu
126  Isabelle Kocher
127  Frans Muller
128  Brickman David M CPA
129  Xu Heyi
130  Chansin Treenuchagron
131  Kazuhiro Tsuga
132  David P. Abney
133  Marvin Ellison
134  Yu Xubo
135  Bob Swan
136  Megan Brennan
137  Chang Zhenming
138  Xu Jiayin
139  Liu Qiangdong
140  Jiao Kaihe
141  Ke Ruiwen
142
143  Thierry Bolloré
144  Yang Xingqiang
145  Joachim Wenning
146  David S. Taylor
147  Masumi Kakinoki
148  Gregory J. Hayes
149  Chen Derong
150  Ren Deqi
151  Luo Ronghuai
152  Frederick W. Smith
153
154
155  Juan Ricardo Luciano
156  Charles F. Lowrey
157  Tatsuo Yasunaga
158  Wan Zulkiflee
159  Ryūichi Isaka
160  Shashi Shanker
161  Yan Zhiyong
162
163  Severin Schwan
164  Edgard Bonte
165
166
167
168
169  She Lulin
170  Robert Allen Iger
171
172  Kevin P. Hourican
173  Enrique J. Lores
174  Frédéric Oudéa
175  Nicke Widyawati
176  José María Álvarez-Pallete López (José María Álvarez-Pallete)
177
178  Tomoaki Kobayakawa
179  Bruce D. Broussard
180  Bruce Flatt
181  Chen Jianhua
182  Daniel Zhang
183  Rolf Martin Schmitz
184  Mark Zuckerberg
185
186
187  Sidney Toledano
188  Tian Huiyu
189
190  Jim Umpleby
191  Candido Botelho Bracher
192  Carlos Brito
193
194  Kelcy Warren
195  Robert G. Scott
196
197  Marillyn Hewson
198  Albert Bourla
199
200  Josu Jon Imaz
201  Vasant Narasimhan
202  Zhang Yuliang
203  Song Zhiping
204  David M. Solomon
205  Elmar Degenhart
206  Xavier Huillard
207
208
209
210  Brian P. Hannasch
211  Li Weimin
212  Yang Yuanqing
213  Tao Yiping
214
215  Guido Kerkhoff
216  Gao Guofu
217
218  James P. Gorman
219  Gilberto Tomazoni
220  Li Shufu
221  Octavio de Lazari
222  Yasuyoshi Karasawa
223  Laurent Mignon
224
225  Chuck Robbins
226  Pierre-André de Chalendar
227  Han-Woo Park
228  Stéphane Richard
229  David Cordani
230
231  Masayuki Hyodo
232  Zheng Wanchun
233
234  Onur Genç
235  Brian Duperreault
236  Rajnish Kumar
237  Ma Huateng
238  Mario Greco
239  Christian Sewing
240  Werner Baumann
241  Samuel N. Hazen
242  Zhang Zhengao
243  Hu Wenming
244  Li Jianhong
245
246  Andrew Stewart Mackenzie
247  Gregory A. Heckman
248  Antoine Lissowski
249  Wang Tingge
250  Zhang Xiaolum
251  Yu Dehui
252  Yousef Al-Benyan
253  Martin Lundstedt
254  Zhu Jiusheng
255  Herman Gref
256  David I. McKay
257  Doug Parker
258  Kuok Khoon Hong
259  Syh-Jang Liao
260  Ed Bastian
261
262  Wang Xiaochu
263
264  Tom Rutledge
265  Guenter Butschek
266  Wolf-Henning Scheider
268
269  Rubem de Freitas Novaes
270  Stephen Squeri
271
272
273  Zhang Bo
274  Sergio Ermotti
275
276
277  Huang Wenzhou
278  David H. Long
279  Xu Lirong
280
281  Yang Zhaoqian
282  Torsten Leue
283  Zhou Qiang
284
285  Kenneth C. Frazier
286  Shu Yinbiao
287  Martin Bouygues
288  Olivier Brandicourt
289
290  Darius E. Adamczyk
291  Xu Xiaoxi
292  José Ignacio Sánchez Galán
293  Oscar Munoz
294  Søren Skou
295  Bharat Masrani
296  Emma Walmsley
297  Roger W. Ferguson Jr.
298  Julie Sweet
299  Donald J. Walker
300
301
302  Ian McIntosh
303  Jean-Sébastien Jacques
304
305  Pedro Guimarães
306
307  Safra Catz
308  Thomas J. Wilson
309  Michael J. Kasbar
310  Ralph Hamers
311  Iain Conn
312  Paul Fang
313
314  Roger W. Crandall
315  Carlo Messina
316  Bhavesh V. Patel
317
318  Li Xiyong
319  Ryan Lance
320  Jes Staley
321  Mike Coupe
322  Gao Hongwei
323
324  Akio Negishi
325
326  Guillaume Pepy
327  Takeo Higuchi
328  Peter Voser
329  John C. May
330  Richard T. Hume
331  André Desmarais
332  Christian Mumenthaler
333  Hou Enlong
334  Seiji Izumisawa
335  Seok-Hee Lee
336  Eduardo de Salles Bartolomeo
337  A. James Teague
338  Zhang Shuili
339  Kiyotaka Ise
340
341  John Donahoe
342
343  Phebe Novakovic
344
345  Fujio Mitarai
346
347  Yang GuoZhan
348  Johannes Teyssen
349
350
351
352  Li Tzar Kuoi, Victor /Fok Kin Ning, Canning
353
354  Shunichi Kito
355  Matteo Del Fante
356  Koji Kakigi
357  Toshihiro Suzuki
358  Long Ziping
359  Sun Yongcai
360  Tidjane Thiam
361  Sun Jianfen
362  Qian Zhimin
363
364
365  Barry Lam
366  Wilfred C.W. Chiang
367  Gong Yande
368  Lin Tengjiao
369  Wang Yongqian
370  Xiong Qun Li
371  Nobuaki Kurumatani
372  Michael A. Wells
373  Matt Comyn
374  Masaaki Tsuya
375  Rui Xiaowu
376  Sae-Hong Huh
377  Kengo Sakurada
378  Masahiro Hashimoto
379  Olivier Le Peuch
380  Michael F. Roman
381  Richard A. Gonzalez
382  Evan G. Greenberg
383  Jay D. Debertin
384  Jack Bowles
385  Yao Lin
386  Wen Shugang
387  Richard Fairbank
388  Ng Keng Hooi
389  Akira Marumoto
390
391  Tricia Griffith
392  Cornelius Riese /Uwe Fr_hlich
393  Chung-Kook Park
394  Shun-Chin Lee
395  James Quincey
396  Jean Paul Agon
397  Albert Manifold
398
399
400  Wayne Peacock
401  Benjamin M. Smith
402  Zhang Gongyan
403  Dominic Blakemore
404  Antonio Neri
405  Philip Jansen
406  Pablo Isla
407  Antoine Frérot
408  Miles D. White
409  Sanjay Mehrotra
410  Daniel Obajtek
411  Jean-Pascal Tricoire
412  Oliver Windholz
413  Alan D. Schnitzer
414  Dong Mingzhu
415  Joos Sutter
416  Kathy J. Warden
417  Mark S. Little
418
419  Omar Ishrak
420  Shigeki Iwane
421
422  André Calantzopoulos
423  Levent Çakıroğlu (Levent Cakiroglu)
424  Simon Lin
425  Jean Pierre Mustier
426  Sung-Chul Hyun
427  Bill McDermott
428  Philippe Wahl
429
430  Francisco Reynés Massanet
431  Fabrice Zumbrunnen
432  Emmanuel Faber
433
434  Jong Kyoo Yoon
435  William M. Walsh
436  Shuichi Watanabe
437  Masayoshi Matsumoto
438  Chen Feihu
439  Shang Jiqiang
440  Tomomi Nakamura
441  Gao Dengbang
442
443  Manuel Bartlett
444  Jung-Suk Koh /Young-Ho Lee
445  Alain Dehaze
446  Jacques van den Broek
447  Jan Jenisch
448  Liang Haishan
449
450  Mark Cutifani
451
452  Antonio Huertas
453  Satoru Katsuno
454  Thomas J. Nimbley
455  Ming-Ho Hsiung
456  Vincent Bolloré
457  Shayne Elliott
458  Yuki Fukasawa
459  Rainer Seele
460  Thomas A. Kennedy
461  Gong Huadong
462
463  Kyung-Shik Sohn /Keun-Hee Park
464  Guo Jingang
465  Wang Maosheng
466  Rajeev Suri
467  Jean-François van Boxmeer
468  Lei Jun
469  Zhai Hong
470  Takashi Niino
471  Richard M. Tsai
472  Miguel Patricio
473
474  Revathi Advaithi
475  Zhang Yalin
476
477  Jörn H. Werner
478  Florent Menrgaux
479  Philip W. Chronican
480  Dirk Van de Put
481  Kasper Rørsted
482  Li Hongshuang
483  Wiebe Draijer
484
485  Xu Xianping
486  Andrew J. Cecere
487  Jeffrey Gennette
488  Miguel Eduardo Padilla Silva
489  Todd J. Vasos
490  H.C. Shin
491  Gerald W. Schwartz
492  Bao Lang Chen
493  Philippe Petitcolin
494  Willem A.J. van Duin
495  Rajesh J. Mehta
496  Leon J. Topalian
497  Darryl White
498
499  Frederico Pinheiro Fleury Curado
500  Benoît Potier

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           value
1    Born: October 17, 1966 (age 53 years), Memphis, TN', 'Nationality: American', 'Spouse: Shelley McMillon', 'Education: Bentonville High School, Sam M. Walton College of Business, The University of Tulsa, University of Arkansas', 'Children: Blake McMillon, Spencer McMillon', 'Parents: Morris McMillon, Laura McMillon
2    Null
3    Born: April 23, 1958 (age 61 years), Netherlands', 'Full name: Bernardus Cornelis Adriana Margriet van Beurden', 'Spouse: Stacey van Beurden', 'Children: 4', 'Term: January 2014–present', 'Education: Delft University of Technology (TU Delft)
4
5
6    Born: 1960 (age 60 years)', 'Nationality: Saudi', 'Education: جامعة الملك فهد للبترول والمعادن
7    Born: September 14, 1955 (age 64 years), Queens, New York, NY', 'Nationality: American', 'Spouse: Mary Dudley', 'Citizenship: United Kingdom; United States', 'Title: Former Group Chief Executive of BP', 'Education: University of Illinois at Urbana-Champaign, MORE
8    Born: Wichita, KS', 'Nationality: American', 'Spouse: Kathryn Woods', 'Predecessor: Rex W. Tillerson', 'Education: Kellogg School of Management, Texas A&M University
9    Born: October 24, 1958 (age 61 years), Munich, Germany', 'Education: Technische Universität München (1987), MORE', 'Board member of: Audi, Volkswagen Group, SEAT, Škoda Auto, Porsche Holding
10   Born: May 3, 1956 (age 63 years), Nagoya, Aichi, Japan', 'Nationality: Japanese', 'Children: 2', 'Education: Babson College, Keio University', 'Parents: Shoichiro Toyoda, Hiroko Mitsui', 'Grandparents: Kiichiro Toyoda, Hatako Toyoda
11   Born: November 1, 1960 (age 59 years), Mobile, AL', 'Height: 6′ 0″', 'Net worth: US$ 1.3 billion (2015)', 'Education: The Fuqua School of Business (1988), MORE', 'Parents: Geraldine Cook, Donald Cook', 'Siblings: Gerald Cook, Michael Cook
12   Born: August 30, 1930 (age 89 years), Omaha, NE', 'Net worth: 74.3 billion USD (2020)', 'Education: Columbia Business School (1950–1951), MORE', 'Spouse: Astrid Menks (m. 2006), Susan Buffett (m. 1952–2004)
13   Born: January 12, 1964 (age 56 years), Albuquerque, NM', 'Height: 5′ 7″', 'Nationality: American', 'Net worth: 124 billion USD (2020)', 'Education: Princeton University (1986), River Oaks Elementary School, Miami Palmetto Senior High School', 'Parents: Ted Jorgensen, Miguel Bezos, Jacklyn Bezos
14
15
16   Born: January 1957 (age 63 years), Johannesburg, South Africa', 'Net worth: 2.8 billion USD (2020)', 'Spouse: Elana Glasenberg', 'Children: 2', 'Education: Marshall Business School, USC, University of the Witwatersrand, Johannesburg, University of Southern California', 'Nationality: Swiss, Israeli, South African, Australian
17   Null
18   Born: June 11, 1969 (age 50 years), Västervik, Sweden', 'Nationality: Swedish', 'Employer: Daimler AG', 'Education: University of St. Gallen, Stockholm School of Economics, Danderyds gymnasium
19   Born: 1956 (age 64 years), Pittsburgh, PA', 'Nationality: American', 'Spouse: Lee Ann Merlo', 'Education: University of Pittsburgh School of Pharmacy (1978)', 'Residence: Rhode Island
20   Born: June 24, 1963 (age 56 years), Le Petit-Quevilly, France', 'Education: École Polytechnique
21
22   Born: 1964 (age 56 years), Melbourne, Australia', 'Education: University of Melbourne', 'Predecessor: Claude Dauphin
23   Born: October 18, 1950 (age 69 years), Banqiao District, Taipei, Taiwan', 'Net worth: 5.8 billion USD (2020)', 'Spouse: Delia Tseng (m. 2008), Serena Lin (m. 1974–2005)', 'Education: Taipei College of Maritime Technology (1966–1971), New Taipei Municipal Panchiao Senior High School', 'Children: Gou Shou-zheng, Gou Xiao-ling, Gou Shou-shan, Gou Xiao-ru', 'Organizations founded: Hon Hai Precision Industry Co., Ltd., Hon Hai Precision, Yonglin Foundation, FIH Mobile Limited
24   Born: April 1, 1976 (age 44 years), New York, NY', 'Spouse: Lavinia Borromeo (m. 2004)', 'Education: Polytechnic University of Turin', 'Siblings: Lapo Elkann, Ginevra Elkann, Anna de Pahlen, Maria de Pahlen, Pietro de Pahlen, Tatiana de Pahlen, Sofia de Pahlen', 'Children: Oceano Noah Elkann, Vita Talita Elkann, Leone Mosé Elkann', 'Parents: Alain Elkann, Margherita Agnelli
25   Born: April 22, 1960 (age 59 years), Oklahoma City, OK', 'Nationality: American', 'Spouse: Lenise Stephenson', 'Children: 2', 'Residence: Dallas, TX', 'Education: The University of Oklahoma, University of Central Oklahoma
26
27   Born: 1961 (age 59 years), South Africa', 'Education: University of the Witwatersrand, Johannesburg', 'Predecessor: R. David Yost
28   Born: 1960 (age 60 years)', 'Education: University of Colorado Boulder
29   Born: December 1955 (age 64 years), China', 'Education: Zhongnan University of Economics and Law', 'Organization founded: Ping An Insurance
30   Born: April 22, 1955 (age 64 years), Columbus, OH', 'Nationality: American', 'Education: University of Michigan (1977)', 'Spouse: Kathy Hackett', 'Residence: Grand Rapids, Michigan, U.S', 'Children: 2
31   Null
32   Born: December 24, 1961 (age 58 years), Waterford, MI', 'Nationality: American', 'Spouse: Anthony E. Barra', 'Education: Stanford Graduate School of Business (1988–1990), Kettering University, Mott High School', 'Children: Nicholas Barra, Rachel Barra', 'Parents: Ray Makela, Eva Makela
33   Born: July 31, 1955 (age 64 years), Hyogo, Japan', 'Education: Hyogo Prefectural Nagata High School
34   Born: May 19, 1959 (age 60 years), Japan', 'Alma mater: Tokyo City University', 'Board member of: Honda Motor Company
35   Born: August 8, 1952 (age 67 years), California', 'Nationality: American', 'Education: San Diego State University (1975)', 'Predecessor: James Sinegal
36   Null
37   Born: June 10, 1972 (age 47 years), Madurai, India', 'Spouse: Anjali Pichai', 'Education: Wharton School of the University of Pennsylvania, MORE', 'Children: Kavya Pichai, Kiran Pichai', 'Nationality: American, Indian', 'Parents: Regunatha Pichai, Lakshmi Pichai
38   Null
39
40   Born: June 4, 1941 (age 78 years), Pescara, Italy', 'Net worth: 8.8 billion USD (2020)', 'Children: 2', 'Partner: Ornella Barra (1985–)', 'Board member of: Walgreens Boots Alliance', 'Education: University of Milan, Politecnico di Milano
41   Born: March 13, 1956 (age 64 years), New York, NY', 'Nationality: American', 'Net worth: 1.2 billion USD (2020)', 'Spouse: Judith Kent (m. 1983)', 'Children: Laura Dimon, Julia Dimon, Kara Leigh Dimon', 'Education: Harvard Business School (1982), Tufts University, Browning School
42
43
44   Null
45   Born: March 1, 1965 (age 55 years), Bergisch Gladbach, Germany', 'Education: University of Cologne (1988–1993), NYU Stern School of Business (1988–1993)
46   Born: March 24, 1973 (age 47 years), Cologne, Germany', 'Education: WHU - Otto Beisheim School of Management, Lancaster University, University of St. Gallen
47   Born: July 25, 1960 (age 59 years), Pineville, KY', 'Education: University of Kentucky', 'Predecessor: David Dillon', 'Board member of: Cincinnati Financial, Kroger
48   Born: 1964 (age 56 years), Washington, D.C.', 'Nationality: American', 'Children: 3', 'Title: Chairman and CEO, General Electric', 'Predecessor: John L. Flannery', 'Education: Washington College, Harvard Business School
49   Null
50
51
52   Born: November 18, 1948 (age 71 years), Otaru, Hokkaido, Japan', 'Education: Hitotsubashi University', 'Predecessor: Taizo Nishimuro
53   Born: October 13, 1965 (age 54 years), Freiburg im Breisgau, Germany', 'Education: RWTH Aachen University (1991), MORE
54   Spouse(s): married', 'Education: Texas A&M University', 'Children: 4
55   Null
56   Born: 1959 (age 61 years), China', 'Education: Beijing University of Posts and Telecommunications
57   Born: May 1957 (age 62 years)', 'Education: University of Missouri-St. Louis, Our Lady of the Lake School of Business
58   Born: October 9, 1959 (age 60 years), Marietta, OH', 'Nationality: American', 'Spouse: Susan Berry', 'Children: 3', 'Education: Notre Dame Law School (1984), Brown University (1981), University of Notre Dame', 'Siblings: Patrick Moynihan, Kathryn Moynihan
59   Null
60   Born: August 19, 1967 (age 52 years), Hyderabad, India', 'Title: CEO of Microsoft', 'Spouse: Anupama Nadella (m. 1992)', 'Education: University of Wisconsin-Milwaukee (1990), MORE', "Books: Hit Refresh: The Quest to Rediscover Microsoft's Soul and Imagine a Better Future for Everyone", 'Children: Tara Nadella, Zain Nadella, Divya Nadella
61   Born: October 25, 1944 (age 75 years), Zhenning Buyei and Miao Autonomous County, Anshun, China', 'Height: 5′ 8″', 'Spouse: Yao Ling', 'Net worth: 1.1 billion USD (2020)', 'Education: Chongqing University', 'Children: Meng Wanzhou, Annabel Yao, Ren Ping
62   Born: 1958 (age 62 years), Flint, MI', 'Nationality: American', 'Education: Eli Broad College of Business, Central High School, Michigan State University
63
64   Born: July 30, 1955 (age 64 years)', 'Predecessor: Hiroo Unoura
65   Born: December 12, 1949 (age 70 years), Osaka, Osaka, Japan
66   Born: November 14, 1953 (age 66 years), Japan
67   Born: May 1958 (age 61 years)', 'Education: Dongbei University of Finance and Economics', 'Party: Communist Party of China
68   Born: April 18, 1957 (age 62 years), Philadelphia, PA', 'Nationality: American', "Books: How Companies Win: Profiting from Demand-Driven Business Models No Matter What Business You're In", 'Education: Orefield Middle School, Pamplin College of Business, Virginia Polytechnic Institute and State University', "Albums: Momentary Mutiny, Day Drinkin', Salmon Chanted Harbor", 'Children: Corey Calhoun, Amy Calhoun, Devon Calhoun, Jessica Calhoun
69   Born: 1965 (age 55 years)', 'Nationality: American', 'Organization: Visa U.S.A', 'Education: New York University, Johns Hopkins University
70   Born: June 23, 1957 (age 62 years), Arnbruck, Germany', 'Spouse: Rosemarie Kaeser', 'Education: Ostbayerische Technische Hochschule (OTH) Regensburg
71   Born: May 2, 1960 (age 59 years), Bristol, CT', 'Nationality: American', 'Spouse: Donna Corbat', 'Education: Harvard University (1983)
72   Born: Tiffin, OH', 'Education: University of Dayton (1982), Tiffin University (1976)
73   Null
74   Null
75   Born: June 28, 1959 (age 60 years), Philadelphia, PA', 'Nationality: American', 'Net worth: 1.7 billion USD (2020)', 'Spouse: Aileen Roberts', 'Education: Wharton School of the University of Pennsylvania, University of Pennsylvania, Germantown Academy', 'Children: Tucker Roberts, Sarah Roberts
76   Born: September 9, 1965 (age 54 years), Neuwied, Germany', 'Nationality: German', 'Predecessor: Paul Bulcke', 'Citizenship: German and American', 'Education: Harvard Business School, University of St. Gallen

In [60]:
# convert the index to a column and name as company_rank 
df['index1'] = df.index

df = df.rename(columns={'index1': 'company_rank'})


print(df)

                                                               ceo  \
1    Doug McMillon
2    Dai Houliang
3    Ben van Beurden
4
5
6    Amin H. Nasser
7    Bob Dudley
8    Darren Woods
9    Herbert Diess
10   Akio Toyoda
11   Tim Cook
12   Warren Buffett
13   Jeff Bezos
14
15
16   Ivan Glasenberg
17   Brian S. Tyler
18   Ola Källenius
19   Larry J. Merlo
20   Patrick Pouyanné
21
22   Jeremy Weir
23   Terry Gou
24   John Elkann
25   Randall L. Stephenson
26
27   Steven H. Collis
28   Mike Wirth
29   Ma Mingzhe
30   Jim Hackett
31   Tian Guoli
32   Mary T. Barra
33   Takehiko Kakiuchi
34   Takahiro Hachigo
35   W. Craig Jelinek
36   Zhou Mubing
37   Sundar Pichai
38   Michael C. Kaufmann
39
40   Stefano Pessina
41   Jamie Dimon
42
43
44   Liu Liange
45   Oliver Bäte
46   Thomas Buberl
47   Rodney McMullen
48   H. Lawrence Culp Jr.
49   Hugh R. Frater
50
51
52   Masatsugu Nagato
53   Harald Krüger
54   Greg Garland
55   Zhang Zongyan
56   Li Yue
57   Joseph W. Gorder
58   Brian Moynihan
59   Chen Fenjian
60   Satya Nadella
61   Ren Zhengfei
62   Craig Menear
63
64   Jun Sawada
65   Masahiro Okafuji
66   Hiroto Saikawa
67   Zheng Zhijie
68   Dave Calhoun
69   Charles W. Scharf
70   Joe Kaeser
71   Michael Corbat
72   Gary R. Heminger
73   Tae-Won Chey/Dong-Hyun Jang
74   Roberto da Cunha Castello Branco
75   Brian L. Roberts
76   Ulf Mark Schneider
77   Volkmar Denner
78   Andreas Schierenbeck
79   Gail Koziara Boudreaux
80   Wang Xiangming
81   Alexandre Bompard
82   Li Shaozhu
83   Claudio Descalzi
84   Michael S. Dell
85   José Antonio Alvarez (José Antonio Álvarez Álvarez)
86   Igor Sechin
87   Xu Liuping
88   Ning Gaoning
89   Francesco Starace
90   Timotheus Höttges
91   Philippe Brassac
92   Philippe Donnet
93   Liu Qitao
94
95   Octavio Romero Oropeza
96   Carlos Tavares
97   Yan Hao
98   Masayoshi Son
99   John Flint
100  C. Marc Doyle
101  Liu Aili
102  Toshiaki Higashihara
103
104  Jean-Laurent Bonnafé
105  Tsutomu Sugimori
106
107  Wang Xiangxi
108  Michael L. Tipsord
109  Alex Gorsky
110  Jean-Bernard Lévy
111  Meng Zhenping
112  Tang Fuping
113  Eldar Sætre
114  Ginni Rometty
115  Martin Brudermüller
116
117  Sanjiv Singh
118  Motoya Okada
119  Wang Wenyin
120  Lakshmi Mittal
121
122  Brian Cornell
123  Guillaume Faury
124  Frank Appel
125  Hiroshi Shimizu
126  Isabelle Kocher
127  Frans Muller
128  Brickman David M CPA
129  Xu Heyi
130  Chansin Treenuchagron
131  Kazuhiro Tsuga
132  David P. Abney
133  Marvin Ellison
134  Yu Xubo
135  Bob Swan
136  Megan Brennan
137  Chang Zhenming
138  Xu Jiayin
139  Liu Qiangdong
140  Jiao Kaihe
141  Ke Ruiwen
142
143  Thierry Bolloré
144  Yang Xingqiang
145  Joachim Wenning
146  David S. Taylor
147  Masumi Kakinoki
148  Gregory J. Hayes
149  Chen Derong
150  Ren Deqi
151  Luo Ronghuai
152  Frederick W. Smith
153
154
155  Juan Ricardo Luciano
156  Charles F. Lowrey
157  Tatsuo Yasunaga
158  Wan Zulkiflee
159  Ryūichi Isaka
160  Shashi Shanker
161  Yan Zhiyong
162
163  Severin Schwan
164  Edgard Bonte
165
166
167
168
169  She Lulin
170  Robert Allen Iger
171
172  Kevin P. Hourican
173  Enrique J. Lores
174  Frédéric Oudéa
175  Nicke Widyawati
176  José María Álvarez-Pallete López (José María Álvarez-Pallete)
177
178  Tomoaki Kobayakawa
179  Bruce D. Broussard
180  Bruce Flatt
181  Chen Jianhua
182  Daniel Zhang
183  Rolf Martin Schmitz
184  Mark Zuckerberg
185
186
187  Sidney Toledano
188  Tian Huiyu
189
190  Jim Umpleby
191  Candido Botelho Bracher
192  Carlos Brito
193
194  Kelcy Warren
195  Robert G. Scott
196
197  Marillyn Hewson
198  Albert Bourla
199
200  Josu Jon Imaz
201  Vasant Narasimhan
202  Zhang Yuliang
203  Song Zhiping
204  David M. Solomon
205  Elmar Degenhart
206  Xavier Huillard
207
208
209
210  Brian P. Hannasch
211  Li Weimin
212  Yang Yuanqing
213  Tao Yiping
214
215  Guido Kerkhoff
216  Gao Guofu
217
218  James P. Gorman
219  Gilberto Tomazoni
220  Li Shufu
221  Octavio de Lazari
222  Yasuyoshi Karasawa
223  Laurent Mignon
224
225  Chuck Robbins
226  Pierre-André de Chalendar
227  Han-Woo Park
228  Stéphane Richard
229  David Cordani
230
231  Masayuki Hyodo
232  Zheng Wanchun
233
234  Onur Genç
235  Brian Duperreault
236  Rajnish Kumar
237  Ma Huateng
238  Mario Greco
239  Christian Sewing
240  Werner Baumann
241  Samuel N. Hazen
242  Zhang Zhengao
243  Hu Wenming
244  Li Jianhong
245
246  Andrew Stewart Mackenzie
247  Gregory A. Heckman
248  Antoine Lissowski
249  Wang Tingge
250  Zhang Xiaolum
251  Yu Dehui
252  Yousef Al-Benyan
253  Martin Lundstedt
254  Zhu Jiusheng
255  Herman Gref
256  David I. McKay
257  Doug Parker
258  Kuok Khoon Hong
259  Syh-Jang Liao
260  Ed Bastian
261
262  Wang Xiaochu
263
264  Tom Rutledge
265  Guenter Butschek
266  Wolf-Henning Scheider
268
269  Rubem de Freitas Novaes
270  Stephen Squeri
271
272
273  Zhang Bo
274  Sergio Ermotti
275
276
277  Huang Wenzhou
278  David H. Long
279  Xu Lirong
280
281  Yang Zhaoqian
282  Torsten Leue
283  Zhou Qiang
284
285  Kenneth C. Frazier
286  Shu Yinbiao
287  Martin Bouygues
288  Olivier Brandicourt
289
290  Darius E. Adamczyk
291  Xu Xiaoxi
292  José Ignacio Sánchez Galán
293  Oscar Munoz
294  Søren Skou
295  Bharat Masrani
296  Emma Walmsley
297  Roger W. Ferguson Jr.
298  Julie Sweet
299  Donald J. Walker
300
301
302  Ian McIntosh
303  Jean-Sébastien Jacques
304
305  Pedro Guimarães
306
307  Safra Catz
308  Thomas J. Wilson
309  Michael J. Kasbar
310  Ralph Hamers
311  Iain Conn
312  Paul Fang
313
314  Roger W. Crandall
315  Carlo Messina
316  Bhavesh V. Patel
317
318  Li Xiyong
319  Ryan Lance
320  Jes Staley
321  Mike Coupe
322  Gao Hongwei
323
324  Akio Negishi
325
326  Guillaume Pepy
327  Takeo Higuchi
328  Peter Voser
329  John C. May
330  Richard T. Hume
331  André Desmarais
332  Christian Mumenthaler
333  Hou Enlong
334  Seiji Izumisawa
335  Seok-Hee Lee
336  Eduardo de Salles Bartolomeo
337  A. James Teague
338  Zhang Shuili
339  Kiyotaka Ise
340
341  John Donahoe
342
343  Phebe Novakovic
344
345  Fujio Mitarai
346
347  Yang GuoZhan
348  Johannes Teyssen
349
350
351
352  Li Tzar Kuoi, Victor /Fok Kin Ning, Canning
353
354  Shunichi Kito
355  Matteo Del Fante
356  Koji Kakigi
357  Toshihiro Suzuki
358  Long Ziping
359  Sun Yongcai
360  Tidjane Thiam
361  Sun Jianfen
362  Qian Zhimin
363
364
365  Barry Lam
366  Wilfred C.W. Chiang
367  Gong Yande
368  Lin Tengjiao
369  Wang Yongqian
370  Xiong Qun Li
371  Nobuaki Kurumatani
372  Michael A. Wells
373  Matt Comyn
374  Masaaki Tsuya
375  Rui Xiaowu
376  Sae-Hong Huh
377  Kengo Sakurada
378  Masahiro Hashimoto
379  Olivier Le Peuch
380  Michael F. Roman
381  Richard A. Gonzalez
382  Evan G. Greenberg
383  Jay D. Debertin
384  Jack Bowles
385  Yao Lin
386  Wen Shugang
387  Richard Fairbank
388  Ng Keng Hooi
389  Akira Marumoto
390
391  Tricia Griffith
392  Cornelius Riese /Uwe Fr_hlich
393  Chung-Kook Park
394  Shun-Chin Lee
395  James Quincey
396  Jean Paul Agon
397  Albert Manifold
398
399
400  Wayne Peacock
401  Benjamin M. Smith
402  Zhang Gongyan
403  Dominic Blakemore
404  Antonio Neri
405  Philip Jansen
406  Pablo Isla
407  Antoine Frérot
408  Miles D. White
409  Sanjay Mehrotra
410  Daniel Obajtek
411  Jean-Pascal Tricoire
412  Oliver Windholz
413  Alan D. Schnitzer
414  Dong Mingzhu
415  Joos Sutter
416  Kathy J. Warden
417  Mark S. Little
418
419  Omar Ishrak
420  Shigeki Iwane
421
422  André Calantzopoulos
423  Levent Çakıroğlu (Levent Cakiroglu)
424  Simon Lin
425  Jean Pierre Mustier
426  Sung-Chul Hyun
427  Bill McDermott
428  Philippe Wahl
429
430  Francisco Reynés Massanet
431  Fabrice Zumbrunnen
432  Emmanuel Faber
433
434  Jong Kyoo Yoon
435  William M. Walsh
436  Shuichi Watanabe
437  Masayoshi Matsumoto
438  Chen Feihu
439  Shang Jiqiang
440  Tomomi Nakamura
441  Gao Dengbang
442
443  Manuel Bartlett
444  Jung-Suk Koh /Young-Ho Lee
445  Alain Dehaze
446  Jacques van den Broek
447  Jan Jenisch
448  Liang Haishan
449
450  Mark Cutifani
451
452  Antonio Huertas
453  Satoru Katsuno
454  Thomas J. Nimbley
455  Ming-Ho Hsiung
456  Vincent Bolloré
457  Shayne Elliott
458  Yuki Fukasawa
459  Rainer Seele
460  Thomas A. Kennedy
461  Gong Huadong
462
463  Kyung-Shik Sohn /Keun-Hee Park
464  Guo Jingang
465  Wang Maosheng
466  Rajeev Suri
467  Jean-François van Boxmeer
468  Lei Jun
469  Zhai Hong
470  Takashi Niino
471  Richard M. Tsai
472  Miguel Patricio
473
474  Revathi Advaithi
475  Zhang Yalin
476
477  Jörn H. Werner
478  Florent Menrgaux
479  Philip W. Chronican
480  Dirk Van de Put
481  Kasper Rørsted
482  Li Hongshuang
483  Wiebe Draijer
484
485  Xu Xianping
486  Andrew J. Cecere
487  Jeffrey Gennette
488  Miguel Eduardo Padilla Silva
489  Todd J. Vasos
490  H.C. Shin
491  Gerald W. Schwartz
492  Bao Lang Chen
493  Philippe Petitcolin
494  Willem A.J. van Duin
495  Rajesh J. Mehta
496  Leon J. Topalian
497  Darryl White
498
499  Frederico Pinheiro Fleury Curado
500  Benoît Potier

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           value  \
1    Born: October 17, 1966 (age 53 years), Memphis, TN', 'Nationality: American', 'Spouse: Shelley McMillon', 'Education: Bentonville High School, Sam M. Walton College of Business, The University of Tulsa, University of Arkansas', 'Children: Blake McMillon, Spencer McMillon', 'Parents: Morris McMillon, Laura McMillon
2    Null
3    Born: April 23, 1958 (age 61 years), Netherlands', 'Full name: Bernardus Cornelis Adriana Margriet van Beurden', 'Spouse: Stacey van Beurden', 'Children: 4', 'Term: January 2014–present', 'Education: Delft University of Technology (TU Delft)
4
5
6    Born: 1960 (age 60 years)', 'Nationality: Saudi', 'Education: جامعة الملك فهد للبترول والمعادن
7    Born: September 14, 1955 (age 64 years), Queens, New York, NY', 'Nationality: American', 'Spouse: Mary Dudley', 'Citizenship: United Kingdom; United States', 'Title: Former Group Chief Executive of BP', 'Education: University of Illinois at Urbana-Champaign, MORE
8    Born: Wichita, KS', 'Nationality: American', 'Spouse: Kathryn Woods', 'Predecessor: Rex W. Tillerson', 'Education: Kellogg School of Management, Texas A&M University
9    Born: October 24, 1958 (age 61 years), Munich, Germany', 'Education: Technische Universität München (1987), MORE', 'Board member of: Audi, Volkswagen Group, SEAT, Škoda Auto, Porsche Holding
10   Born: May 3, 1956 (age 63 years), Nagoya, Aichi, Japan', 'Nationality: Japanese', 'Children: 2', 'Education: Babson College, Keio University', 'Parents: Shoichiro Toyoda, Hiroko Mitsui', 'Grandparents: Kiichiro Toyoda, Hatako Toyoda
11   Born: November 1, 1960 (age 59 years), Mobile, AL', 'Height: 6′ 0″', 'Net worth: US$ 1.3 billion (2015)', 'Education: The Fuqua School of Business (1988), MORE', 'Parents: Geraldine Cook, Donald Cook', 'Siblings: Gerald Cook, Michael Cook
12   Born: August 30, 1930 (age 89 years), Omaha, NE', 'Net worth: 74.3 billion USD (2020)', 'Education: Columbia Business School (1950–1951), MORE', 'Spouse: Astrid Menks (m. 2006), Susan Buffett (m. 1952–2004)
13   Born: January 12, 1964 (age 56 years), Albuquerque, NM', 'Height: 5′ 7″', 'Nationality: American', 'Net worth: 124 billion USD (2020)', 'Education: Princeton University (1986), River Oaks Elementary School, Miami Palmetto Senior High School', 'Parents: Ted Jorgensen, Miguel Bezos, Jacklyn Bezos
14
15
16   Born: January 1957 (age 63 years), Johannesburg, South Africa', 'Net worth: 2.8 billion USD (2020)', 'Spouse: Elana Glasenberg', 'Children: 2', 'Education: Marshall Business School, USC, University of the Witwatersrand, Johannesburg, University of Southern California', 'Nationality: Swiss, Israeli, South African, Australian
17   Null
18   Born: June 11, 1969 (age 50 years), Västervik, Sweden', 'Nationality: Swedish', 'Employer: Daimler AG', 'Education: University of St. Gallen, Stockholm School of Economics, Danderyds gymnasium
19   Born: 1956 (age 64 years), Pittsburgh, PA', 'Nationality: American', 'Spouse: Lee Ann Merlo', 'Education: University of Pittsburgh School of Pharmacy (1978)', 'Residence: Rhode Island
20   Born: June 24, 1963 (age 56 years), Le Petit-Quevilly, France', 'Education: École Polytechnique
21
22   Born: 1964 (age 56 years), Melbourne, Australia', 'Education: University of Melbourne', 'Predecessor: Claude Dauphin
23   Born: October 18, 1950 (age 69 years), Banqiao District, Taipei, Taiwan', 'Net worth: 5.8 billion USD (2020)', 'Spouse: Delia Tseng (m. 2008), Serena Lin (m. 1974–2005)', 'Education: Taipei College of Maritime Technology (1966–1971), New Taipei Municipal Panchiao Senior High School', 'Children: Gou Shou-zheng, Gou Xiao-ling, Gou Shou-shan, Gou Xiao-ru', 'Organizations founded: Hon Hai Precision Industry Co., Ltd., Hon Hai Precision, Yonglin Foundation, FIH Mobile Limited
24   Born: April 1, 1976 (age 44 years), New York, NY', 'Spouse: Lavinia Borromeo (m. 2004)', 'Education: Polytechnic University of Turin', 'Siblings: Lapo Elkann, Ginevra Elkann, Anna de Pahlen, Maria de Pahlen, Pietro de Pahlen, Tatiana de Pahlen, Sofia de Pahlen', 'Children: Oceano Noah Elkann, Vita Talita Elkann, Leone Mosé Elkann', 'Parents: Alain Elkann, Margherita Agnelli
25   Born: April 22, 1960 (age 59 years), Oklahoma City, OK', 'Nationality: American', 'Spouse: Lenise Stephenson', 'Children: 2', 'Residence: Dallas, TX', 'Education: The University of Oklahoma, University of Central Oklahoma
26
27   Born: 1961 (age 59 years), South Africa', 'Education: University of the Witwatersrand, Johannesburg', 'Predecessor: R. David Yost
28   Born: 1960 (age 60 years)', 'Education: University of Colorado Boulder
29   Born: December 1955 (age 64 years), China', 'Education: Zhongnan University of Economics and Law', 'Organization founded: Ping An Insurance
30   Born: April 22, 1955 (age 64 years), Columbus, OH', 'Nationality: American', 'Education: University of Michigan (1977)', 'Spouse: Kathy Hackett', 'Residence: Grand Rapids, Michigan, U.S', 'Children: 2
31   Null
32   Born: December 24, 1961 (age 58 years), Waterford, MI', 'Nationality: American', 'Spouse: Anthony E. Barra', 'Education: Stanford Graduate School of Business (1988–1990), Kettering University, Mott High School', 'Children: Nicholas Barra, Rachel Barra', 'Parents: Ray Makela, Eva Makela
33   Born: July 31, 1955 (age 64 years), Hyogo, Japan', 'Education: Hyogo Prefectural Nagata High School
34   Born: May 19, 1959 (age 60 years), Japan', 'Alma mater: Tokyo City University', 'Board member of: Honda Motor Company
35   Born: August 8, 1952 (age 67 years), California', 'Nationality: American', 'Education: San Diego State University (1975)', 'Predecessor: James Sinegal
36   Null
37   Born: June 10, 1972 (age 47 years), Madurai, India', 'Spouse: Anjali Pichai', 'Education: Wharton School of the University of Pennsylvania, MORE', 'Children: Kavya Pichai, Kiran Pichai', 'Nationality: American, Indian', 'Parents: Regunatha Pichai, Lakshmi Pichai
38   Null
39
40   Born: June 4, 1941 (age 78 years), Pescara, Italy', 'Net worth: 8.8 billion USD (2020)', 'Children: 2', 'Partner: Ornella Barra (1985–)', 'Board member of: Walgreens Boots Alliance', 'Education: University of Milan, Politecnico di Milano
41   Born: March 13, 1956 (age 64 years), New York, NY', 'Nationality: American', 'Net worth: 1.2 billion USD (2020)', 'Spouse: Judith Kent (m. 1983)', 'Children: Laura Dimon, Julia Dimon, Kara Leigh Dimon', 'Education: Harvard Business School (1982), Tufts University, Browning School
42
43
44   Null
45   Born: March 1, 1965 (age 55 years), Bergisch Gladbach, Germany', 'Education: University of Cologne (1988–1993), NYU Stern School of Business (1988–1993)
46   Born: March 24, 1973 (age 47 years), Cologne, Germany', 'Education: WHU - Otto Beisheim School of Management, Lancaster University, University of St. Gallen
47   Born: July 25, 1960 (age 59 years), Pineville, KY', 'Education: University of Kentucky', 'Predecessor: David Dillon', 'Board member of: Cincinnati Financial, Kroger
48   Born: 1964 (age 56 years), Washington, D.C.', 'Nationality: American', 'Children: 3', 'Title: Chairman and CEO, General Electric', 'Predecessor: John L. Flannery', 'Education: Washington College, Harvard Business School
49   Null
50
51
52   Born: November 18, 1948 (age 71 years), Otaru, Hokkaido, Japan', 'Education: Hitotsubashi University', 'Predecessor: Taizo Nishimuro
53   Born: October 13, 1965 (age 54 years), Freiburg im Breisgau, Germany', 'Education: RWTH Aachen University (1991), MORE
54   Spouse(s): married', 'Education: Texas A&M University', 'Children: 4
55   Null
56   Born: 1959 (age 61 years), China', 'Education: Beijing University of Posts and Telecommunications
57   Born: May 1957 (age 62 years)', 'Education: University of Missouri-St. Louis, Our Lady of the Lake School of Business
58   Born: October 9, 1959 (age 60 years), Marietta, OH', 'Nationality: American', 'Spouse: Susan Berry', 'Children: 3', 'Education: Notre Dame Law School (1984), Brown University (1981), University of Notre Dame', 'Siblings: Patrick Moynihan, Kathryn Moynihan
59   Null
60   Born: August 19, 1967 (age 52 years), Hyderabad, India', 'Title: CEO of Microsoft', 'Spouse: Anupama Nadella (m. 1992)', 'Education: University of Wisconsin-Milwaukee (1990), MORE', "Books: Hit Refresh: The Quest to Rediscover Microsoft's Soul and Imagine a Better Future for Everyone", 'Children: Tara Nadella, Zain Nadella, Divya Nadella
61   Born: October 25, 1944 (age 75 years), Zhenning Buyei and Miao Autonomous County, Anshun, China', 'Height: 5′ 8″', 'Spouse: Yao Ling', 'Net worth: 1.1 billion USD (2020)', 'Education: Chongqing University', 'Children: Meng Wanzhou, Annabel Yao, Ren Ping
62   Born: 1958 (age 62 years), Flint, MI', 'Nationality: American', 'Education: Eli Broad College of Business, Central High School, Michigan State University
63
64   Born: July 30, 1955 (age 64 years)', 'Predecessor: Hiroo Unoura
65   Born: December 12, 1949 (age 70 years), Osaka, Osaka, Japan
66   Born: November 14, 1953 (age 66 years), Japan
67   Born: May 1958 (age 61 years)', 'Education: Dongbei University of Finance and Economics', 'Party: Communist Party of China
68   Born: April 18, 1957 (age 62 years), Philadelphia, PA', 'Nationality: American', "Books: How Companies Win: Profiting from Demand-Driven Business Models No Matter What Business You're In", 'Education: Orefield Middle School, Pamplin College of Business, Virginia Polytechnic Institute and State University', "Albums: Momentary Mutiny, Day Drinkin', Salmon Chanted Harbor", 'Children: Corey Calhoun, Amy Calhoun, Devon Calhoun, Jessica Calhoun
69   Born: 1965 (age 55 years)', 'Nationality: American', 'Organization: Visa U.S.A', 'Education: New York University, Johns Hopkins University
70   Born: June 23, 1957 (age 62 years), Arnbruck, Germany', 'Spouse: Rosemarie Kaeser', 'Education: Ostbayerische Technische Hochschule (OTH) Regensburg
71   Born: May 2, 1960 (age 59 years), Bristol, CT', 'Nationality: American', 'Spouse: Donna Corbat', 'Education: Harvard University (1983)
72   Born: Tiffin, OH', 'Education: University of Dayton (1982), Tiffin University (1976)
73   Null
74   Null
75   Born: June 28, 1959 (age 60 years), Philadelphia, PA', 'Nationality: American', 'Net worth: 1.7 billion USD (2020)', 'Spouse: Aileen Roberts', 'Education: Wharton School of the University of Pennsylvania, University of Pennsylvania, Germantown Academy', 'Children: Tucker Roberts, Sarah Roberts
76   Born: September 9, 1965 (age 54 years), Neuwied, Germany', 'Nationality: German', 'Predecessor: Paul Bulcke', 'Citizenship: German and American', 'Education: Harvard Business School, University of St. Gallen

In [61]:
#reindex the data as starting from 1 to 499
re_index = pd.Series(range(1,500))  
df = df.set_index([re_index])

In [62]:
display(df)

,ceo,value,company_rank
1,Doug McMillon,"Born: October 17, 1966 (age 53 years), Memphis, TN', 'Nationality: American', 'Spouse: Shelley McMillon', 'Education: Bentonville High School, Sam M. Walton College of Business, The University of Tulsa, University of Arkansas', 'Children: Blake McMillon, Spencer McMillon', 'Parents: Morris McMillon, Laura McMillon",1
2,Dai Houliang,Null,2
3,Ben van Beurden,"Born: April 23, 1958 (age 61 years), Netherlands', 'Full name: Bernardus Cornelis Adriana Margriet van Beurden', 'Spouse: Stacey van Beurden', 'Children: 4', 'Term: January 2014–present', 'Education: Delft University of Technology (TU Delft)",3
4,,,4
5,,,5
6,Amin H. Nasser,"Born: 1960 (age 60 years)', 'Nationality: Saudi', 'Education: جامعة الملك فهد للبترول والمعادن",6
7,Bob Dudley,"Born: September 14, 1955 (age 64 years), Queens, New York, NY', 'Nationality: American', 'Spouse: Mary Dudley', 'Citizenship: United Kingdom; United States', 'Title: Former Group Chief Executive of BP', 'Education: University of Illinois at Urbana-Champaign, MORE",7
8,Darren Woods,"Born: Wichita, KS', 'Nationality: American', 'Spouse: Kathryn Woods', 'Predecessor: Rex W. Tillerson', 'Education: Kellogg School of Management, Texas A&M University",8
9,Herbert Diess,"Born: October 24, 1958 (age 61 years), Munich, Germany', 'Education: Technische Universität München (1987), MORE', 'Board member of: Audi, Volkswagen Group, SEAT, Škoda Auto, Porsche Holding",9
10,Akio Toyoda,"Born: May 3, 1956 (age 63 years), Nagoya, Aichi, Japan', 'Nationality: Japanese', 'Children: 2', 'Education: Babson College, Keio University', 'Parents: Shoichiro Toyoda, Hiroko Mitsui', 'Grandparents: Kiichiro Toyoda, Hatako Toyoda",10
11,Tim Cook,"Born: November 1, 1960 (age 59 years), Mobile, AL', 'Height: 6′ 0″', 'Net worth: US$ 1.3 billion (2015)', 'Education: The Fuqua School of Business (1988), MORE', 'Parents: Geraldine Cook, Donald Cook', 'Siblings: Gerald Cook, Michael Cook",11
12,Warren Buffett,"Born: August 30, 1930 (age 89 years), Omaha, NE', 'Net worth: 74.3 billion USD (2020)', 'Education: Columbia Business School (1950–1951), MORE', 'Spouse: Astrid Menks (m. 2006), Susan Buffett (m. 1952–2004)",12
13,Jeff Bezos,"Born: January 12, 1964 (age 56 years), Albuquerque, NM', 'Height: 5′ 7″', 'Nationality: American', 'Net worth: 124 billion USD (2020)', 'Education: Princeton University (1986), River Oaks Elementary School, Miami Palmetto Senior High School', 'Parents: Ted Jorgensen, Miguel Bezos, Jacklyn Bezos",13
14,,,14
15,,,15
16,Ivan Glasenberg,"Born: January 1957 (age 63 years), Johannesburg, South Africa', 'Net worth: 2.8 billion USD (2020)', 'Spouse: Elana Glasenberg', 'Children: 2', 'Education: Marshall Business School, USC, University of the Witwatersrand, Johannesburg, University of Southern California', 'Nationality: Swiss, Israeli, South African, Australian",16
17,Brian S. Tyler,Null,17
18,Ola Källenius,"Born: June 11, 1969 (age 50 years), Västervik, Sweden', 'Nationality: Swedish', 'Employer: Daimler AG', 'Education: University of St. Gallen, Stockholm School of Economics, Danderyds gymnasium",18
19,Larry J. Merlo,"Born: 1956 (age 64 years), Pittsburgh, PA', 'Nationality: American', 'Spouse: Lee Ann Merlo', 'Education: University of Pittsburgh School of Pharmacy (1978)', 'Residence: Rhode Island",19
20,Patrick Pouyanné,"Born: June 24, 1963 (age 56 years), Le Petit-Quevilly, France', 'Education: École Polytechnique",20
21,,,21
22,Jeremy Weir,"Born: 1964 (age 56 years), Melbourne, Australia', 'Education: University of Melbourne', 'Predecessor: Claude Dauphin",22
23,Terry Gou,"Born: October 18, 1950 (age 69 years), Banqiao District, Taipei, Taiwan', 'Net worth: 5.8 billion USD (2020)', 'Spouse: Delia Tseng (m. 2008), Serena Lin (m. 1974–2005)', 'Education: Taipei College of Maritime Technology (1966–1971), New Taipei Municipal Panchiao Senior High School', 'Children: Gou Shou-zheng, Gou Xiao-ling, Gou Shou-shan, Gou Xiao-ru', 'Organizations founded: Hon Hai Precision Industry Co., Ltd., Hon Hai Precision, Yonglin Foundation, FIH Mobile Limited",23
24,John Elkann,"Born: April 1, 1976 (age 44 years), New York, NY', 'Spouse: Lavinia Borromeo (m. 2004)', 'Education: Polytechnic University of Turin', 'Siblings: Lapo Elkann, Ginevra Elkann, Anna de Pahlen, Maria de Pahlen, Pietro de Pahlen, Tatiana de Pahlen, Sofia de Pahlen', 'Children: Oceano Noah Elkann, Vita Talita Elkann, Leone Mosé Elkann', 'Parents: Alain Elkann, Margherita Agnelli",24
25,Randall L. Stephenson,"Born: April 22, 1960 (age 59 years), Oklahoma City, OK', 'Nationality: American', 'Spouse: Lenise Stephenson', 'Children: 2', 'Residence: Dallas, TX', 'Education: The University of Oklahoma, University of Central Oklahoma",25
26,,,26
27,Steven H. Collis,"Born: 1961 (age 59 years), South Africa', 'Education: University of the Witwatersrand, Johannesburg', 'Predecessor: R. David Yost",27
28,Mike Wirth,"Born: 1960 (age 60 years)', 'Education: University of Colorado Boulder",28
29,Ma Mingzhe,"Born: December 1955 (age 64 years), China', 'Education: Zhongnan University of Economics and Law', 'Organization founded: Ping An Insurance",29
30,Jim Hackett,"Born: April 22, 1955 (age 64 years), Columbus, OH', 'Nationality: American', 'Education: University of Michigan (1977)', 'Spouse: Kathy Hackett', 'Residence: Grand Rapids, Michigan, U.S', 'Children: 2",30
31,Tian Guoli,Null,31
32,Mary T. Barra,"Born: December 24, 1961 (age 58 years), Waterford, MI', 'Nationality: American', 'Spouse: Anthony E. Barra', 'Education: Stanford Graduate School of Business (1988–1990), Kettering University, Mott High School', 'Children: Nicholas Barra, Rachel Barra', 'Parents: Ray Makela, Eva Makela",32
33,Takehiko Kakiuchi,"Born: July 31, 1955 (age 64 years), Hyogo, Japan', 'Education: Hyogo Prefectural Nagata High School",33
34,Takahiro Hachigo,"Born: May 19, 1959 (age 60 years), Japan', 'Alma mater: Tokyo City University', 'Board member of: Honda Motor Company",34
35,W. Craig Jelinek,"Born: August 8, 1952 (age 67 years), California', 'Nationality: American', 'Education: San Diego State University (1975)', 'Predecessor: James Sinegal",35
36,Zhou Mubing,Null,36
37,Sundar Pichai,"Born: June 10, 1972 (age 47 years), Madurai, India', 'Spouse: Anjali Pichai', 'Education: Wharton School of the University of Pennsylvania, MORE', 'Children: Kavya Pichai, Kiran Pichai', 'Nationality: American, Indian', 'Parents: Regunatha Pichai, Lakshmi Pichai",37
38,Michael C. Kaufmann,Null,38
39,,,39
40,Stefano Pessina,"Born: June 4, 1941 (age 78 years), Pescara, Italy', 'Net worth: 8.8 billion USD (2020)', 'Children: 2', 'Partner: Ornella Barra (1985–)', 'Board member of: Walgreens Boots Alliance', 'Education: University of Milan, Politecnico di Milano",40
41,Jamie Dimon,"Born: March 13, 1956 (age 64 years), New York, NY', 'Nationality: American', 'Net worth: 1.2 billion USD (2020)', 'Spouse: Judith Kent (m. 1983)', 'Children: Laura Dimon, Julia Dimon, Kara Leigh Dimon', 'Education: Harvard Business School (1982), Tufts University, Browning School",41
42,,,42
43,,,43
44,Liu Liange,Null,44
45,Oliver Bäte,"Born: March 1, 1965 (age 55 years), Bergisch Gladbach, Germany', 'Education: University of Cologne (1988–1993), NYU Stern School of Business (1988–1993)",45
46,Thomas Buberl,"Born: March 24, 1973 (age 47 years), Cologne, Germany', 'Education: WHU - Otto Beisheim School of Management, Lancaster University, University of St. Gallen",46
47,Rodney McMullen,"Born: July 25, 1960 (age 59 years), Pineville, KY', 'Education: University of Kentucky', 'Predecessor: David Dillon', 'Board member of: Cincinnati Financial, Kroger",47
48,H. Lawrence Culp Jr.,"Born: 1964 (age 56 years), Washington, D.C.', 'Nationality: American', 'Children: 3', 'Title: Chairman and CEO, General Electric', 'Predecessor: John L. Flannery', 'Education: Washington College, Harvard Business School",48
49,Hugh R. Frater,Null,49
50,,,50
51,,,51
52,Masatsugu Nagato,"Born: November 18, 1948 (age 71 years), Otaru, Hokkaido, Japan', 'Education: Hitotsubashi University', 'Predecessor: Taizo Nishimuro",52
53,Harald Krüger,"Born: October 13, 1965 (age 54 years), Freiburg im Breisgau, Germany', 'Education: RWTH Aachen University (1991), MORE",53
54,Greg Garland,"Spouse(s): married', 'Education: Texas A&M University', 'Children: 4",54
55,Zhang Zongyan,Null,55
56,Li Yue,"Born: 1959 (age 61 years), China', 'Education: Beijing University of Posts and Telecommunications",56
57,Joseph W. Gorder,"Born: May 1957 (age 62 years)', 'Education: University of Missouri-St. Louis, Our Lady of the Lake School of Business",57
58,Brian Moynihan,"Born: October 9, 1959 (age 60 years), Marietta, OH', 'Nationality: American', 'Spouse: Susan Berry', 'Children: 3', 'Education: Notre Dame Law School (1984), Brown University (1981), University of Notre Dame', 'Siblings: Patrick Moynihan, Kathryn Moynihan",58
59,Chen Fenjian,Null,59
60,Satya Nadella,"Born: August 19, 1967 (age 52 years), Hyderabad, India', 'Title: CEO of Microsoft', 'Spouse: Anupama Nadella (m. 1992)', 'Education: University of Wisconsin-Milwaukee (1990), MORE', ""Books: Hit Refresh: The Quest to Rediscover Microsoft's Soul and Imagine a Better Future for Everyone"", 'Children: Tara Nadella, Zain Nadella, Divya Nadella",60
61,Ren Zhengfei,"Born: October 25, 1944 (age 75 years), Zhenning Buyei and Miao Autonomous County, Anshun, China', 'Height: 5′ 8″', 'Spouse: Yao Ling', 'Net worth: 1.1 billion USD (2020)', 'Education: Chongqing University', 'Children: Meng Wanzhou, Annabel Yao, Ren Ping",61
62,Craig Menear,"Born: 1958 (age 62 years), Flint, MI', 'Nationality: American', 'Education: Eli Broad College of Business, Central High School, Michigan State University",62
63,,,63
64,Jun Sawada,"Born: July 30, 1955 (age 64 years)', 'Predecessor: Hiroo Unoura",64
65,Masahiro Okafuji,"Born: December 12, 1949 (age 70 years), Osaka, Osaka, Japan",65
66,Hiroto Saikawa,"Born: November 14, 1953 (age 66 years), Japan",66
67,Zheng Zhijie,"Born: May 1958 (age 61 years)', 'Education: Dongbei University of Finance and Economics', 'Party: Communist Party of China",67
68,Dave Calhoun,"Born: April 18, 1957 (age 62 years), Philadelphia, PA', 'Nationality: American', ""Books: How Companies Win: Profiting from Demand-Driven Business Models No Matter What Business You're In"", 'Education: Orefield Middle School, Pamplin College of Business, Virginia Polytechnic Institute and State University', ""Albums: Momentary Mutiny, Day Drinkin', Salmon Chanted Harbor"", 'Children: Corey Calhoun, Amy Calhoun, Devon Calhoun, Jessica Calhoun",68
69,Charles W. Scharf,"Born: 1965 (age 55 years)', 'Nationality: American', 'Organization: Visa U.S.A', 'Education: New York University, Johns Hopkins University",69
70,Joe Kaeser,"Born: June 23, 1957 (age 62 years), Arnbruck, Germany', 'Spouse: Rosemarie Kaeser', 'Education: Ostbayerische Technische Hochschule (OTH) Regensburg",70
71,Michael Corbat,"Born: May 2, 1960 (age 59 years), Bristol, CT', 'Nationality: American', 'Spouse: Donna Corbat', 'Education: Harvard University (1983)",71
72,Gary R. Heminger,"Born: Tiffin, OH', 'Education: University of Dayton (1982), Tiffin University (1976)",72
73,Tae-Won Chey/Dong-Hyun Jang,Null,73
74,Roberto da Cunha Castello Branco,Null,74
75,Brian L. Roberts,"Born: June 28, 1959 (age 60 years), Philadelphia, PA', 'Nationality: American', 'Net worth: 1.7 billion USD (2020)', 'Spouse: Aileen Roberts', 'Education: Wharton School of the University of Pennsylvania, University of Pennsylvania, Germantown Academy', 'Children: Tucker Roberts, Sarah Roberts",75
76,Ulf Mark Schneider,"Born: September 9, 1965 (age 54 years), Neuwied, Germany', 'Nationality: German', 'Predecessor: Paul Bulcke', 'Citizenship: German and American', 'Education: Harvard Business School, University of St. Gallen",76
77,Volkmar Denner,"Born: November 30, 1956 (age 63 years), Uhingen, Germany', 'Education: University of Stuttgart (1985), University of Stuttgart (1981)', 'Appointed by: Angela Merkel",77
78,Andreas Schierenbeck,Null,78
79,Gail Koziara Boudreaux,"Born: 1960 (age 60 years)', 'Spouse: Terry Boudreaux (m. 1989)', 'Children: 2 sons', 'Education: Chicopee Comprehensv High Sch, Columbia University, Columbia Business School, Dartmouth College",79
80,Wang Xiangming,Null,80
81,Alexandre Bompard,"Born: October 4, 1972 (age 47 years), Saint-Étienne, France', 'Spouse: Charlotte Bompard', 'Predecessor: Georges Plassat', 'Board member of: Fnac', ""Education: École Nationale d'Administration (1997–1999), Sciences Po""",81
82,Li Shaozhu,Null,82
83,Claudio Descalzi,"Born: 1955 (age 65 years), Milan, Italy', 'Education: University of Milan",83
84,Michael S. Dell,"Born: February 23, 1965 (age 55 years), Houston, TX', 'Spouse: Susan Dell (m. 1989)', 'Education: Memorial Senior High School, The University of Texas at Austin, Herod Elementary School', 'Children: Alexa Dell, Zachary Dell, Kira Dell, Juliette Dell', 'Parents: Alexander Dell, Lorraine Charlotte Dell",84
85,José Antonio Alvarez (José Antonio Álvarez Álvarez),"Born: January 6, 1960 (age 60 years), León, Spain', 'Predecessor: Javier Marín",85
86,Igor Sechin,"Born: September 7, 1960 (age 59 years), Russian Soviet Federative Socialist Republic', 'Height: 5′ 9″', 'Spouse: Olga Rozhkova (m. 2011–2017)', 'Education: Saint Petersburg State University', 'Children: Inga Sechina, Ivan Sechin', 'Nationality: Russian, Soviet",86
87,Xu Liuping,Null,87
88,Ning Gaoning,"Born: November 9, 1958 (age 61 years), Binzhou, China', 'Education: Joseph M. Katz Graduate School of Business, Shandong University, University of Pittsburgh",88
89,Francesco Starace,"Born: 1955 (age 65 years), Rome, Italy', 'Education: Politecnico di Milano",89
90,Timotheus Höttges,"Born: September 18, 1962 (age 57 years), Solingen, Germany', 'Education: University of Cologne",90
91,Philippe Brassac,"Born: August 31, 1959 (age 60 years), Nîmes, France', 'Education: ENSAE Paris', 'Predecessor: Jean-Paul Chifflet",91
92,Philippe Donnet,"Born: July 26, 1960 (age 59 years), Suresnes, France', 'Education: École Polytechnique",92
93,Liu Qitao,Null,93
94,,,94
95,Octavio Romero Oropeza,"Born: January 20, 1959 (age 61 years), Jalapa",95
96,Carlos Tavares,"Born: August 14, 1958 (age 61 years), Lisbon, Portugal', 'Nationality: Portuguese', 'Education: École Centrale Paris (1981)",96
97,Yan Hao,Null,97
98,Masayoshi Son,"Born: August 11, 1957 (age 62 years), Tosu, Saga, Japan', 'Nationality: Japanese', 'Net worth: 20.3 billion USD (2020)', 'Children: 2', 'Spouse: Masami Ohno (m. 1979)', 'Education: University of California, Berkeley (1980), MORE",98
99,John Flint,"Born: June 1968 (age 51 years), Yorkshire, United Kingdom', 'Successor: Noel Quinn', 'Predecessor: Stuart Gulliver', 'Children: 2', 'Title: CEO, HSBC', 'Education: University of Portsmouth, Giggleswick School",99
100,C. Marc Doyle,Null,100
101,Liu Aili,Null,101
102,Toshiaki Higashihara,Null,102
103,,,103
104,Jean-Laurent Bonnafé,"Born: July 14, 1961 (age 58 years), Clichy, France', 'Education: École Polytechnique, Lycée Louis-le-Grand",104
105,Tsutomu Sugimori,Null,105
106,,,106
107,Wang Xiangxi,Null,107
108,Michael L. Tipsord,"Born: June 20, 1959 (age 60 years), Illinois', 'Education: Illinois Wesleyan University (1981), University of Illinois at Urbana-Champaign",108
109,Alex Gorsky,"Born: May 24, 1960 (age 59 years), Kansas City, KS', 'Nationality: American', 'Salary: US$ 20.1 million (2018); US$ 29.8 million (2017)', 'Education: Wharton School of the University of Pennsylvania, United States Military Academy', 'Children: Nicholas Gorsky', 'Parents: Albert Gorsky, Loretta Gorsky",109
110,Jean-Bernard Lévy,"Born: March 18, 1955 (age 65 years), Suresnes, France', 'Education: École Polytechnique, Télécom Paris', 'Parents: Monique Herzog, Claude Lévy",110
111,Meng Zhenping,Null,111
112,Tang Fuping,Null,112
113,Eldar Sætre,"Born: February 8, 1956 (age 64 years), Vartdal, Norway', 'Education: NHH Norwegian School of Economics', 'Siblings: Oddrun Godø",113
114,Ginni Rometty,"Born: July 29, 1957 (age 62 years), Chicago, IL', 'Full name: Virginia Marie Rometty', 'Nationality: American', 'Spouse: Mark Anthony Rometty', 'Education: Robert R. McCormick School of Engineering and Applied Science at Northwestern', 'Siblings: Joe Nicosia",114
115,Martin Brudermüller,"Born: May 5, 1961 (age 58 years), Stuttgart, Germany', 'Education: Karlsruhe Institute of Technology', 'Predecessor: Kurt Bock', 'Term: 2018",115
116,,,116
117,Sanjiv Singh,Null,117
118,Motoya Okada,"Born: June 17, 1951 (age 68 years), Yokkaichi, Mie, Japan', 'Education: Babson College', 'Parents: Takuya Okada', 'Siblings: Katsuya Okada",118
119,Wang Wenyin,"Born: 1968 (age 52 years), Anhui, China', 'Net worth: 8.1 billion USD (2020)', 'Education: Anhui Qianshan Yezhai Middle School, Nanjing University', 'Organization founded: Amer International Group",119
120,Lakshmi Mittal,"Born: June 15, 1950 (age 69 years), Sadulpur, India', 'Nationality: Indian', 'Net worth: 8.9 billion USD (2020)', 'Spouse: Usha Mittal', ""Education: St. Xavier's College, Kolkata"", 'Children: Vanisha Mittal, Aditya Mittal",120
121,,,121
122,Brian Cornell,"Born: 1958 (age 62 years), Queens, New York, NY', 'Spouse: Martha Cornell', 'Predecessor: Gregg W. Steinhafel', 'Known for: Chairman & CEO of Target', 'Education: UCLA Anderson School of Management, University of California, Los Angeles', 'Children: Megan Cornell, Jonathan Cornell",122
123,Guillaume Faury,"Born: February 22, 1968 (age 52 years), Cherbourg-Octeville, Cherbourg-en-Cotentin, France', ""Education: Institut supérieur de l'aéronautique et de l'espace, École nationale supérieure de l'aéronautique et de l'espace""",123
124,Frank Appel,"Born: July 29, 1961 (age 58 years), Hamburg, Germany', 'Predecessor: Klaus Zumwinkel', 'Education: ETH Zürich (2001), Ludwig Maximilian University of Munich",124
125,Hiroshi Shimizu,"Born: March 28, 1903', 'Died: June 23, 1966, Ukyo Ward, Kyoto, Japan', 'Education: Hokkaido University', 'Other name: Takahiko Minamoto, Umihiko Yuhara', 'Books: Japan and Singapore in the world economy",125
126,Isabelle Kocher,"Born: December 9, 1966 (age 53 years), Neuilly-sur-Seine, France', 'Children: 5', 'Spouse: Laurent Kocher (m. 1989)', 'Education: École Normale Supérieure (1987), Mines ParisTech",126
127,Frans Muller,"Education: Erasmus University Rotterdam', 'Predecessor: Dick Boer",127
128,Brickman David M CPA,"Address: 270 Madison Ave # 1500, New York, NY 10016', 'Phone: (212) 687-7215",128
129,Xu Heyi,Null,129
130,Chansin Treenuchagron,Null,130
131,Kazuhiro Tsuga,"Born: November 14, 1956 (age 63 years), Osaka, Osaka, Japan', 'Predecessor: Fumio Ōtsubo', 'Employer: Panasonic', 'Title: President', 'Education: University of California, Santa Barbara (1986), Osaka University (1979)",131
132,David P. Abney,"Born: 1956 (age 64 years), Greenwood, MS', 'Spouse: Sherry Abney', 'Education: Delta State University, Pillow Academy",132
133,Marvin Ellison,"Born: 1966 (age 54 years)', 'Nationality: American', 'Spouse: Sharyn Ellison', 'Profession: Musician', ""Education: Haywood High School, Emory University, Emory University's Goizueta Business School, University of Memphis"", 'Children: Donavan Ellison",133
134,Yu Xubo,Null,134
135,Bob Swan,"Born: May 9, 1960 (age 59 years), Syracuse, NY', 'Spouse(s): married', 'Children: 2', 'Employer: Intel', 'Board member of: Intel Corporation, eBay', 'Education: Corcoran High School, Binghamton University, University at Buffalo School of Management",135
136,Megan Brennan,"Born: 1961 (age 59 years), Pottsville, PA', 'Office: United States Postmaster General since 2015', 'Party: Democratic Party', 'Education: MIT Sloan School of Management, Immaculata University",136
137,Chang Zhenming,"Born: October 1956 (age 63 years), China', 'Parents: Chang Dong', 'Education: Tsinghua University High School, Beijing International Studies University', 'People also search for: Larry Yung, Chang Dong, Qingping Li, Qian Zhang, Deshun Sun, Guoqiang Cao, Guoxin Su",137

Clear rows. Select the rows having values only

In [63]:
#Select the rows with values only to proceed RegEx
df_n = df[df.ceo.notnull()]

df_nv = df_n[(df_n['value'] != 'Null')]

Splite the 'value' column using regex

Succeed to split the values. However, only some of the should be selected: Born, Nationality, and Education

In [64]:
# For Born
df_nv['Born'] = df_nv['value'].str.extract(r"Born: (.+?)\'\," )

# For Nationality 
df_nv['Nationality'] = df_nv['value'].str.extract(r"Nationality: (.+?)\'\," )


# For Education
## Select the strings end with "', '" and the strings end with nothing
Education = df_nv['value'].str.extract(r"Education: (.+?)\'\,\s\'|Education: (.+)?|Alma mater: (.+?)\'\,\s\'")

## merge the extracted two columes
df_nv['Education'] = pd.concat([Education[0].dropna(), Education[1].dropna(), Education[2].dropna()]).reindex_like(Education)

#See the full contents of the rows of value
pd.set_option('display.max_colwidth', -1)

C:\Users\Jeeho\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Jeeho\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\Jeeho\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

Extract only Birth of Year only as BoY

In [65]:
df_nv['BoY'] = df_nv['Born'].str.extract(pat = "([0-9]{4})" )

C:\Users\Jeeho\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

Extract Nationality strings from Born based on 1) the postal abbreviations of the US and 2) the country names

In [66]:
# Create a list of the abbr

us_postal_abbr = {'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 
                  'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 
                  'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 
                  'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 
                  'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WY'}

reorder the index to run the for loop

In [67]:
df_nv_index = pd.Series(range(len(df_nv)))

In [68]:
df_nv = df_nv.set_index([df_nv_index])

In [69]:
# Create a column for the extracted us abbreviation code 
df_nv['us_abbr'] = df_nv['Born'].str.extract(pat = "([A-Z]{2})")

# Insert value 'American' in the 'Nationality' column if where the us_abbr matchs with the list of abbr
df_nv.loc[df_nv['us_abbr'].isin(us_postal_abbr), 'Nationality'] = 'American'

For nationalities

In [70]:
pd.set_option('display.max_rows', None)

Catch the missing countries among the values

In [71]:
#Extract the United States and United Kingdom and the other country names
bn = df_nv['Born'].str.extract(".*?([A-Za-z]{6}\s[A-Za-z]{6,7})$|.*?([A-Za-z]{5,11})$")

## merge the extracted two columes
df_nv['born_country'] = pd.concat([bn[0].dropna(), bn[1].dropna()]).reindex_like(bn)

#Replacing the NaN values of Nationality column with newly extracted values 
df_nv['Nationality'].fillna(df_nv['born_country'], inplace=True)

In [72]:
#drop value, us_abbr, and born_coutry columns
df_nv = df_nv.drop(['value', 'us_abbr', 'born_country'], axis = 1)

In [73]:
display(df_nv)

,ceo,company_rank,Born,Nationality,Education,BoY
0,Doug McMillon,1,"October 17, 1966 (age 53 years), Memphis, TN",American,"Bentonville High School, Sam M. Walton College of Business, The University of Tulsa, University of Arkansas",1966
1,Ben van Beurden,3,"April 23, 1958 (age 61 years), Netherlands",Netherlands,Delft University of Technology (TU Delft),1958
2,,4,NaN,NaN,NaN,NaN
3,,5,NaN,NaN,NaN,NaN
4,Amin H. Nasser,6,1960 (age 60 years),Saudi,جامعة الملك فهد للبترول والمعادن,1960
5,Bob Dudley,7,"September 14, 1955 (age 64 years), Queens, New York, NY",American,"University of Illinois at Urbana-Champaign, MORE",1955
6,Darren Woods,8,"Wichita, KS",American,"Kellogg School of Management, Texas A&M University",NaN
7,Herbert Diess,9,"October 24, 1958 (age 61 years), Munich, Germany",Germany,"Technische Universität München (1987), MORE",1958
8,Akio Toyoda,10,"May 3, 1956 (age 63 years), Nagoya, Aichi, Japan",Japanese,"Babson College, Keio University",1956
9,Tim Cook,11,"November 1, 1960 (age 59 years), Mobile, AL",American,"The Fuqua School of Business (1988), MORE",1960
10,Warren Buffett,12,"August 30, 1930 (age 89 years), Omaha, NE",American,"Columbia Business School (1950–1951), MORE",1930
11,Jeff Bezos,13,"January 12, 1964 (age 56 years), Albuquerque, NM",American,"Princeton University (1986), River Oaks Elementary School, Miami Palmetto Senior High School",1964
12,,14,NaN,NaN,NaN,NaN
13,,15,NaN,NaN,NaN,NaN
14,Ivan Glasenberg,16,"January 1957 (age 63 years), Johannesburg, South Africa",Africa,"Marshall Business School, USC, University of the Witwatersrand, Johannesburg, University of Southern California",1957
15,Ola Källenius,18,"June 11, 1969 (age 50 years), Västervik, Sweden",Swedish,"University of St. Gallen, Stockholm School of Economics, Danderyds gymnasium",1969
16,Larry J. Merlo,19,"1956 (age 64 years), Pittsburgh, PA",American,University of Pittsburgh School of Pharmacy (1978),1956
17,Patrick Pouyanné,20,"June 24, 1963 (age 56 years), Le Petit-Quevilly, France",France,École Polytechnique,1963
18,,21,NaN,NaN,NaN,NaN
19,Jeremy Weir,22,"1964 (age 56 years), Melbourne, Australia",Australia,University of Melbourne,1964
20,Terry Gou,23,"October 18, 1950 (age 69 years), Banqiao District, Taipei, Taiwan",Taiwan,"Taipei College of Maritime Technology (1966–1971), New Taipei Municipal Panchiao Senior High School",1950
21,John Elkann,24,"April 1, 1976 (age 44 years), New York, NY",American,Polytechnic University of Turin,1976
22,Randall L. Stephenson,25,"April 22, 1960 (age 59 years), Oklahoma City, OK",American,"The University of Oklahoma, University of Central Oklahoma",1960
23,,26,NaN,NaN,NaN,NaN
24,Steven H. Collis,27,"1961 (age 59 years), South Africa",Africa,"University of the Witwatersrand, Johannesburg",1961
25,Mike Wirth,28,1960 (age 60 years),NaN,University of Colorado Boulder,1960
26,Ma Mingzhe,29,"December 1955 (age 64 years), China",China,Zhongnan University of Economics and Law,1955
27,Jim Hackett,30,"April 22, 1955 (age 64 years), Columbus, OH",American,University of Michigan (1977),1955
28,Mary T. Barra,32,"December 24, 1961 (age 58 years), Waterford, MI",American,"Stanford Graduate School of Business (1988–1990), Kettering University, Mott High School",1961
29,Takehiko Kakiuchi,33,"July 31, 1955 (age 64 years), Hyogo, Japan",Japan,Hyogo Prefectural Nagata High School,1955
30,Takahiro Hachigo,34,"May 19, 1959 (age 60 years), Japan",Japan,Tokyo City University,1959
31,W. Craig Jelinek,35,"August 8, 1952 (age 67 years), California",American,San Diego State University (1975),1952
32,Sundar Pichai,37,"June 10, 1972 (age 47 years), Madurai, India","American, Indian","Wharton School of the University of Pennsylvania, MORE",1972
33,,39,NaN,NaN,NaN,NaN
34,Stefano Pessina,40,"June 4, 1941 (age 78 years), Pescara, Italy",Italy,"University of Milan, Politecnico di Milano",1941
35,Jamie Dimon,41,"March 13, 1956 (age 64 years), New York, NY",American,"Harvard Business School (1982), Tufts University, Browning School",1956
36,,42,NaN,NaN,NaN,NaN
37,,43,NaN,NaN,NaN,NaN
38,Oliver Bäte,45,"March 1, 1965 (age 55 years), Bergisch Gladbach, Germany",Germany,"University of Cologne (1988–1993), NYU Stern School of Business (1988–1993)",1965
39,Thomas Buberl,46,"March 24, 1973 (age 47 years), Cologne, Germany",Germany,"WHU - Otto Beisheim School of Management, Lancaster University, University of St. Gallen",1973
40,Rodney McMullen,47,"July 25, 1960 (age 59 years), Pineville, KY",American,University of Kentucky,1960
41,H. Lawrence Culp Jr.,48,"1964 (age 56 years), Washington, D.C.",American,"Washington College, Harvard Business School",1964
42,,50,NaN,NaN,NaN,NaN
43,,51,NaN,NaN,NaN,NaN
44,Masatsugu Nagato,52,"November 18, 1948 (age 71 years), Otaru, Hokkaido, Japan",Japan,Hitotsubashi University,1948
45,Harald Krüger,53,"October 13, 1965 (age 54 years), Freiburg im Breisgau, Germany",Germany,"RWTH Aachen University (1991), MORE",1965
46,Greg Garland,54,NaN,NaN,Texas A&M University,NaN
47,Li Yue,56,"1959 (age 61 years), China",China,Beijing University of Posts and Telecommunications,1959
48,Joseph W. Gorder,57,May 1957 (age 62 years),NaN,"University of Missouri-St. Louis, Our Lady of the Lake School of Business",1957
49,Brian Moynihan,58,"October 9, 1959 (age 60 years), Marietta, OH",American,"Notre Dame Law School (1984), Brown University (1981), University of Notre Dame",1959
50,Satya Nadella,60,"August 19, 1967 (age 52 years), Hyderabad, India",India,"University of Wisconsin-Milwaukee (1990), MORE', ""Books: Hit Refresh: The Quest to Rediscover Microsoft's Soul and Imagine a Better Future for Everyone"", 'Children: Tara Nadella, Zain Nadella, Divya Nadella",1967
51,Ren Zhengfei,61,"October 25, 1944 (age 75 years), Zhenning Buyei and Miao Autonomous County, Anshun, China",China,Chongqing University,1944
52,Craig Menear,62,"1958 (age 62 years), Flint, MI",American,"Eli Broad College of Business, Central High School, Michigan State University",1958
53,,63,NaN,NaN,NaN,NaN
54,Jun Sawada,64,"July 30, 1955 (age 64 years)",NaN,NaN,1955
55,Masahiro Okafuji,65,NaN,NaN,NaN,NaN
56,Hiroto Saikawa,66,NaN,NaN,NaN,NaN
57,Zheng Zhijie,67,May 1958 (age 61 years),NaN,Dongbei University of Finance and Economics,1958
58,Dave Calhoun,68,"April 18, 1957 (age 62 years), Philadelphia, PA",American,"Orefield Middle School, Pamplin College of Business, Virginia Polytechnic Institute and State University', ""Albums: Momentary Mutiny, Day Drinkin', Salmon Chanted Harbor"", 'Children: Corey Calhoun, Amy Calhoun, Devon Calhoun, Jessica Calhoun",1957
59,Charles W. Scharf,69,1965 (age 55 years),American,"New York University, Johns Hopkins University",1965
60,Joe Kaeser,70,"June 23, 1957 (age 62 years), Arnbruck, Germany",Germany,Ostbayerische Technische Hochschule (OTH) Regensburg,1957
61,Michael Corbat,71,"May 2, 1960 (age 59 years), Bristol, CT",American,Harvard University (1983),1960
62,Gary R. Heminger,72,"Tiffin, OH",American,"University of Dayton (1982), Tiffin University (1976)",NaN
63,Brian L. Roberts,75,"June 28, 1959 (age 60 years), Philadelphia, PA",American,"Wharton School of the University of Pennsylvania, University of Pennsylvania, Germantown Academy",1959
64,Ulf Mark Schneider,76,"September 9, 1965 (age 54 years), Neuwied, Germany",German,"Harvard Business School, University of St. Gallen",1965
65,Volkmar Denner,77,"November 30, 1956 (age 63 years), Uhingen, Germany",Germany,"University of Stuttgart (1985), University of Stuttgart (1981)",1956
66,Gail Koziara Boudreaux,79,1960 (age 60 years),NaN,"Chicopee Comprehensv High Sch, Columbia University, Columbia Business School, Dartmouth College",1960
67,Alexandre Bompard,81,"October 4, 1972 (age 47 years), Saint-Étienne, France",France,"École Nationale d'Administration (1997–1999), Sciences Po""",1972
68,Claudio Descalzi,83,"1955 (age 65 years), Milan, Italy",Italy,University of Milan,1955
69,Michael S. Dell,84,"February 23, 1965 (age 55 years), Houston, TX",American,"Memorial Senior High School, The University of Texas at Austin, Herod Elementary School",1965
70,José Antonio Alvarez (José Antonio Álvarez Álvarez),85,"January 6, 1960 (age 60 years), León, Spain",Spain,NaN,1960
71,Igor Sechin,86,"September 7, 1960 (age 59 years), Russian Soviet Federative Socialist Republic",Republic,Saint Petersburg State University,1960
72,Ning Gaoning,88,"November 9, 1958 (age 61 years), Binzhou, China",China,"Joseph M. Katz Graduate School of Business, Shandong University, University of Pittsburgh",1958
73,Francesco Starace,89,"1955 (age 65 years), Rome, Italy",Italy,Politecnico di Milano,1955
74,Timotheus Höttges,90,"September 18, 1962 (age 57 years), Solingen, Germany",Germany,University of Cologne,1962
75,Philippe Brassac,91,"August 31, 1959 (age 60 years), Nîmes, France",France,ENSAE Paris,1959
76,Philippe Donnet,92,"July 26, 1960 (age 59 years), Suresnes, France",France,École Polytechnique,1960
77,,94,NaN,NaN,NaN,NaN
78,Octavio Romero Oropeza,95,NaN,NaN,NaN,NaN
79,Carlos Tavares,96,"August 14, 1958 (age 61 years), Lisbon, Portugal",Portuguese,École Centrale Paris (1981),1958
80,Masayoshi Son,98,"August 11, 1957 (age 62 years), Tosu, Saga, Japan",Japanese,"University of California, Berkeley (1980), MORE",1957
81,John Flint,99,"June 1968 (age 51 years), Yorkshire, United Kingdom",United Kingdom,"University of Portsmouth, Giggleswick School",1968
82,,103,NaN,NaN,NaN,NaN
83,Jean-Laurent Bonnafé,104,"July 14, 1961 (age 58 years), Clichy, France",France,"École Polytechnique, Lycée Louis-le-Grand",1961
84,,106,NaN,NaN,NaN,NaN
85,Michael L. Tipsord,108,"June 20, 1959 (age 60 years), Illinois",Illinois,"Illinois Wesleyan University (1981), University of Illinois at Urbana-Champaign",1959
86,Alex Gorsky,109,"May 24, 1960 (age 59 years), Kansas City, KS",American,"Wharton School of the University of Pennsylvania, United States Military Academy",1960
87,Jean-Bernard Lévy,110,"March 18, 1955 (age 65 years), Suresnes, France",France,"École Polytechnique, Télécom Paris",1955
88,Eldar Sætre,113,"February 8, 1956 (age 64 years), Vartdal, Norway",Norway,NHH Norwegian School of Economics,1956
89,Ginni Rometty,114,"July 29, 1957 (age 62 years), Chicago, IL",American,Robert R. McCormick School of Engineering and Applied Science at Northwestern,1957
90,Martin Brudermüller,115,"May 5, 1961 (age 58 years), Stuttgart, Germany",Germany,Karlsruhe Institute of Technology,1961
91,,116,NaN,NaN,NaN,NaN
92,Motoya Okada,118,"June 17, 1951 (age 68 years), Yokkaichi, Mie, Japan",Japan,Babson College,1951
93,Wang Wenyin,119,"1968 (age 52 years), Anhui, China",China,"Anhui Qianshan Yezhai Middle School, Nanjing University",1968
94,Lakshmi Mittal,120,"June 15, 1950 (age 69 years), Sadulpur, India",Indian,"St. Xavier's College, Kolkata"", 'Children: Vanisha Mittal, Aditya Mittal",1950
95,,121,NaN,NaN,NaN,NaN
96,Brian Cornell,122,"1958 (age 62 years), Queens, New York, NY",American,"UCLA Anderson School of Management, University of California, Los Angeles",1958
97,Guillaume Faury,123,"February 22, 1968 (age 52 years), Cherbourg-Octeville, Cherbourg-en-Cotentin, France",France,"Institut supérieur de l'aéronautique et de l'espace, École nationale supérieure de l'aéronautique et de l'espace""",1968
98,Frank Appel,124,"July 29, 1961 (age 58 years), Hamburg, Germany",Germany,"ETH Zürich (2001), Ludwig Maximilian University of Munich",1961
99,Hiroshi Shimizu,125,"March 28, 1903",NaN,Hokkaido University,1903
100,Isabelle Kocher,126,"December 9, 1966 (age 53 years), Neuilly-sur-Seine, France",France,"École Normale Supérieure (1987), Mines ParisTech",1966
101,Frans Muller,127,NaN,NaN,Erasmus University Rotterdam,NaN
102,Brickman David M CPA,128,NaN,NaN,NaN,NaN
103,Kazuhiro Tsuga,131,"November 14, 1956 (age 63 years), Osaka, Osaka, Japan",Japan,"University of California, Santa Barbara (1986), Osaka University (1979)",1956
104,David P. Abney,132,"1956 (age 64 years), Greenwood, MS",American,"Delta State University, Pillow Academy",1956
105,Marvin Ellison,133,1966 (age 54 years),American,"Haywood High School, Emory University, Emory University's Goizueta Business School, University of Memphis"", 'Children: Donavan Ellison",1966
106,Bob Swan,135,"May 9, 1960 (age 59 years), Syracuse, NY",American,"Corcoran High School, Binghamton University, University at Buffalo School of Management",1960
107,Megan Brennan,136,"1961 (age 59 years), Pottsville, PA",American,"MIT Sloan School of Management, Immaculata University",1961
108,Chang Zhenming,137,"October 1956 (age 63 years), China",China,"Tsinghua University High School, Beijing International Studies University",1956
109,Xu Jiayin,138,"October 9, 1958 (age 61 years), Taikang County, Zhoukou, China",Chinese,Wuhan University of Science and Technology,1958
110,Liu Qiangdong,139,"Lailongzhen, Suqian, China",China,"China Europe International Business School, Renmin University of China",NaN
111,,142,NaN,NaN,NaN,NaN
112,Thierry Bolloré,143,"May 30, 1963 (age 56 years), France",France,"Master of Business Administration, Paris Dauphine University",1963
113,David S. Taylor,146,"April 20, 1958 (age 61 years), Charlotte, NC",American,"Duke University (1980), West Charlotte High School",1958
114,Gregory J. Hayes,148,United States,United States,"Cornell University, Purdue University, Krannert School of Management",NaN
115,Frederick W. Smith,152,"August 11, 1944 (age 75 years), Marks, MS",American,"Yale University (1962–1966), Memphis University School, Presbyterian Day School",1944
116,,153,NaN,NaN,NaN,NaN
117,,154,NaN,NaN,NaN,NaN
118,Juan Ricardo Luciano,155,"1962 (age 58 years), Argentina",Argentine,Instituto Tecnológico de Buenos Aires,1962
119,Wan Zulkiflee,158,"1961 (age 59 years), Malaysia",Malaysia,Malay College Kuala Kangsar,1961
120,Ryūichi Isaka,159,"October 4, 1957 (age 62 years), Tokyo, Japan",Japan,Aoyama Gakuin,1957
121,,162,NaN,NaN,NaN,NaN
122,Severin Schwan,163,"November 17, 1967 (age 52 years), Austria",Austrian,"University of York, University of Innsbruck",1967
123,,165,NaN,NaN,NaN,NaN
124,,166,NaN,NaN,NaN,NaN
125,,167,NaN,NaN,NaN,NaN
126,,168,NaN,NaN,NaN,NaN
127,Robert Allen Iger,170,"February 10, 1951 (age 69 years), New York, NY",American,"Ithaca College (1973), Oceanside High School, Roy H. Park School of Communications, The Center for Early Education",1951
128,,171,NaN,NaN,NaN,NaN
129,Frédéric Oudéa,174,"July 3, 1963 (age 56 years), Paris, France",France,"Sciences Po, École Nationale d'Administration, École Polytechnique""",1963
130,José María Álvarez-Pallete López (José María Álvarez-Pallete),176,"December 12, 1963 (age 56 years), Madrid, Spain",Spain,"Complutense University of Madrid, IPADE Business School, Université Libre de Bruxelles",1963
131,,177,NaN,NaN,NaN,NaN
132,Bruce D. Broussard,179,1963 (age 57 years),NaN,NaN,1963
133,Bruce Flatt,180,"1965 (age 55 years), Winnipeg, Canada",Canada,NaN,1965
134,Chen Jianhua,181,"March 1956 (age 64 years), Lufeng, Guangdong, Shanwei, China",China,Nanjing Normal University,1956
135,Daniel Zhang,182,"1972 (age 48 years), Shanghai, China",Chinese,Shanghai University of Finance and Economics,1972
136,Rolf Martin Schmitz,183,"June 17, 1957 (age 62 years), Mönchengladbach, Germany",Germany,RWTH Aachen University,1957
137,Mark Zuckerberg,184,"May 14, 1984 (age 35 years), White Plains, NY",American,"Harvard University (2002–2004), MORE",1984
138,,185,NaN,NaN,NaN,NaN
139,,186,NaN,NaN,NaN,NaN
140,Sidney Toledano,187,"July 25, 1951 (age 68 years), Casablanca, Morocco","French, Moroccan",NaN,1951
141,,189,NaN,NaN,NaN,NaN
142,Jim Umpleby,190,"1958 (age 62 years), Highland, IN",American,"Rose-Hulman Institute of Technology (1980), Highland High School",1958
143,Candido Botelho Bracher,191,"December 5, 1958 (age 61 years), State of São Paulo, Brazil",Brazil,"Escola de Administração de Empresas de São Paulo (1980), Santa Cruz School",1958
144,Carlos Brito,192,"1960 (age 60 years), Rio de Janeiro, State of Rio de Janeiro, Brazil",Brazilian,"Stanford Graduate School of Business, Universidade Federal do Rio de Janeiro",1960
145,,193,NaN,NaN,NaN,NaN
146,Kelcy Warren,194,"1955 (age 65 years), Gladewater, TX",American,"White Oak High School, The University of Texas at Arlington",1955
147,,196,NaN,NaN,NaN,NaN
148,Marillyn Hewson,197,"1954 (age 66 years), Junction City, KS",American,"Columbia Business School, The University of Alabama, Harvard Business School",1954
149,Albert Bourla,198,1962 (age 58 years),NaN,NaN,1962
150,,199,NaN,NaN,NaN,NaN
151,Josu Jon Imaz,200,"September 6, 1963 (age 56 years), Zumarraga, Spain",Spain,Campus De Bizkaia - Campus of Biscay,1963
152,Vasant Narasimhan,201,"1976 (age 44 years), Moorestown, NJ",American,"Harvard University, Harvard Kennedy School, Harvard Medical School, The University of Chicago",1976
153,David M. Solomon,204,"1962 (age 58 years), Hartsdale, NY",American,"Hamilton College, Edgemont Jr./Sr. High School",1962
154,Elmar Degenhart,205,"January 29, 1959 (age 61 years), Dossenheim, Germany",Germany,University of Stuttgart,1959
155,Xavier Huillard,206,"June 27, 1954 (age 65 years), Paris, France",France,"École des ponts ParisTech, École Polytechnique",1954
156,,207,NaN,NaN,NaN,NaN
157,,208,NaN,NaN,NaN,NaN
158,,209,NaN,NaN,NaN,NaN
159,Yang Yuanqing,212,"November 12, 1964 (age 55 years), Hefei, China",Chinese,"Shanghai Jiao Tong University, University of Science and Technology of China",1964
160,,214,NaN,NaN,NaN,NaN
161,Guido Kerkhoff,215,"November 22, 1967 (age 52 years), Schüttorf, Germany",Germany,"Saarland University, Bielefeld University",1967
162,,217,NaN,NaN,NaN,NaN
163,James P. Gorman,218,"July 14, 1958 (age 61 years), Melbourne, Australia",Australia,"Columbia Business School, Newman College, University of Melbourne, Columbia University, Xavier College', ""Children: Caroline D'Arcy Gorman, Caroline Gorman"", 'Siblings: Katherine Williams",1958
164,Li Shufu,220,"June 25, 1963 (age 56 years), Taizhou, China",China,"Hubei University of Economics, Yanshan University, Harbin University of Science and Technology",1963
165,,224,NaN,NaN,NaN,NaN
166,Chuck Robbins,225,"Grayson, GA",American,"University of North Carolina at Chapel Hill (1983–1987), Rocky Mt High School",NaN
167,Pierre-André de Chalendar,226,"April 12, 1958 (age 61 years), Vichy, France",France,"ESSEC Business School, Établissement La Rochefoucauld : École, collège, et lycée catholique",1958
168,Stéphane Richard,228,"August 24, 1961 (age 58 years), Gironde, France",France,HEC Paris,1961
169,David Cordani,229,"February 10, 1966 (age 54 years), Waterbury, CT",American,"Texas A&M University, University of Hartford",1966
170,,230,NaN,NaN,NaN,NaN
171,,233,NaN,NaN,NaN,NaN
172,Onur Genç,234,"1974 (age 46 years), Trabzon, Turkey",Turkey,"Tepper School of Business (1995–1997), Boğaziçi University (1991–1995)",1974
173,Brian Duperreault,235,"May 8, 1947 (age 72 years), Hamilton, Bermuda",Bermuda,"Saint Joseph's University, Trenton Catholic Academy""",1947
174,Rajnish Kumar,236,"January 14, 1958 (age 62 years)",NaN,NaN,1958
175,Ma Huateng,237,"October 29, 1971 (age 48 years), Chaoyang, Shantou, China",Chinese,"Shenzhen Middle School, Shenzhen University",1971
176,Mario Greco,238,"June 16, 1959 (age 60 years), Naples, Italy",Italy,"University of Rochester, Sapienza University of Rome",1959
177,Christian Sewing,239,"April 24, 1970 (age 49 years), Bünde, Germany",Germany,"Frankfurt School of Finance & Management (1992–1994), MORE",1970
178,Werner Baumann,240,"October 6, 1962 (age 57 years), Krefeld, Germany",Germany,"University of Cologne, RWTH Aachen University",1962
179,Li Jianhong,244,"March 13, 1975 (age 45 years), China",China,NaN,1975
180,,245,NaN,NaN,NaN,NaN
181,Andrew Stewart Mackenzie,246,"December 20, 1956 (age 63 years), Scotland, United Kingdom",United Kingdom,"University of Bristol, University of St Andrews",1956
182,Yousef Al-Benyan,252,NaN,NaN,NaN,NaN
183,Martin Lundstedt,253,"April 28, 1967 (age 52 years), Mariestad, Sweden",Sweden,Chalmers University of Technology,1967

In [74]:
df_nv.to_csv(r'D:\Yeshiva_Univ\Courses\Capstone_project\CEOs_Culture_project\Data\ceo_information\CEOs_info_v5(Apr_10_2020).csv')